(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.btmOverlay = function() {
	this.initialize(img.btmOverlay);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,262);


(lib.imgF1_600 = function() {
	this.initialize(img.imgF1_600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.imgF2_600 = function() {
	this.initialize(img.imgF2_600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.UOlogo = function() {
	this.initialize(img.UOlogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,106,59);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.thrills = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0368D9").s().p("AIkCEQgcgKgUgTQgTgTgMgaQgLgbAAggQAAggALgaQAMgaATgSQAUgSAcgKQAbgKAgAAQAgAAAbAKQAcAKAUASQAUASALAaQAMAaAAAgQAAAggMAbQgLAagUATQgUATgcAKQgbAKggAAQggAAgbgKgAJKg2QgKAEgHAIQgHAHgEALQgEAKAAANQAAANAEALQAEALAHAHQAHAJAKAEQAKAEALAAQALAAAKgEQAKgEAHgJQAHgHAEgLQAEgLAAgNQAAgNgEgKQgEgLgHgHQgHgIgKgEQgKgEgLAAQgLAAgKAEgACtCDQgbgJgUgTQgUgSgLgbQgMgaAAggQAAgfAMgbQALgaAUgTQATgSAbgKQAbgKAeAAQAgAAAcAKQAcALASARIg1A/QgIgJgMgGQgLgGgRAAQgLAAgKAEQgKAEgIAJQgIAIgFAMQgFALAAANQAAAcAOASQAPARAgABIAMgCIAKgDIAAgUIgsAAIAAhGIB8AAIAACSIgWAKIgaAJIg8AHQggABgbgLgAYyCGIgzhfIgDAAIAABfIhYAAIAAkLIB0AAQAUAAAUADQATAEAPALQAQAJAJASQAKARAAAZQAAAZgMASQgMASgXAKIBEBtgAX7gUIAcgBIAKgDQAFgDADgEQADgEAAgHQAAgIgCgEQgDgEgEgCIgJgDIgfAAgATECGIAAkLIC5AAIAABLIhkAAIAAAXIBeAAIAABFIheAAIAAAZIBrAAIAABLgAPtCGIAAkLIC1AAIAABLIhdAAIAAAcIBTAAIAABJIhSAAIAABbgAMVCGIAAkLIC2AAIAABLIhdAAIAAAcIBSAAIAABJIhSAAIAABbgAgpCGIhLiAIgBAAIAECAIhWAAIAAkLIBaAAIBNCHIABAAIgEiHIBVAAIAAELgAlPCGIAAkLIBbAAIAAELgAobCGIAAkLIBcAAIAAC+IBZAAIAABNgArmCGIAAkLIBbAAIAAC+IBZAAIAABNgAtuCGIAAkLIBbAAIAAELgAvqCGIg0hfIgCAAIAABfIhYAAIAAkLIB0AAQATAAAUADQAUAEAPALQAPAJAKASQAJARAAAZQAAAZgMASQgMASgXAKIBFBtgAwhgUIAcgBIAKgDQAEgDAEgEQADgEAAgHQAAgIgDgEQgCgEgEgCIgKgDIgeAAgAz/CGIAAhmIhKAAIAABmIhbAAIAAkLIBaAAIAABbIBKAAIAAhbIBbAAIAAELgA5XCGIAAi/IhCAAIAAhMIDfAAIAABMIhDAAIAAC/g");
	this.shape.setTransform(0.275,26.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.thrills, new cjs.Rectangle(-168.7,12.4,338,28.4), null);


(lib.IMG_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.imgF2_600();
	this.instance.setTransform(-150,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.IMG_2, new cjs.Rectangle(-150,0,300,600), null);


(lib.IMG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// IMG
	this.instance = new lib.imgF1_600();
	this.instance.setTransform(-150,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.IMG_1, new cjs.Rectangle(-150,0,300,600), null);


(lib.BTN = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0368D9").s().p("ADLA0QgLgEgHgIQgIgHgEgLQgFgKAAgMQAAgMAFgLQAEgKAIgHQAHgHALgEQALgEAMAAQANAAAKAEQALAEAHAHQAJAHAEAKQAEALAAAMQAAAMgEAKQgEALgJAHQgHAIgLAEQgKAEgNAAQgMAAgLgEgADWgdQgGACgEAEQgEAFgCAFQgCAGAAAHQAAAGACAGQACAHAEAEQAEAFAGACQAGADAGAAQAHAAAFgDQAGgCAEgFQAEgEADgHQABgGAAgGQAAgHgBgGQgDgFgEgFQgEgEgGgCQgFgDgHAAQgGAAgGADgAi6A0QgKgEgIgIQgIgHgEgLQgEgKgBgMQABgMAEgLQAEgKAIgHQAIgHAKgEQALgEAMAAQAMAAALAEQALAEAHAHQAJAHAEAKQAEALAAAMQAAAMgEAKQgEALgJAHQgHAIgLAEQgLAEgMAAQgMAAgLgEgAivgdQgGACgEAEQgDAFgDAFQgCAGAAAHQAAAGACAGQADAHADAEQAEAFAGACQAFADAHAAQAHAAAGgDQAFgCAEgFQAEgEADgHQACgGAAgGQAAgHgCgGQgDgFgEgFQgEgEgFgCQgGgDgHAAQgHAAgFADgAk5A0QgLgEgHgIQgIgHgFgLQgEgKAAgMQAAgMAEgLQAFgKAIgHQAHgHALgEQAKgEAMAAQANAAALAEQALAEAHAHQAIAHAEAKQAFALAAAMQAAAMgFAKQgEALgIAHQgHAIgLAEQgLAEgNAAQgMAAgKgEgAkugdQgGACgEAEQgEAFgDAFQgBAGAAAHQAAAGABAGQADAHAEAEQAEAFAGACQAFADAGAAQAIAAAFgDQAGgCAEgFQAEgEACgHQACgGAAgGQAAgHgCgGQgCgFgEgFQgEgEgGgCQgFgDgIAAQgGAAgFADgAGEA1IgVhHIgBAAIgVBHIgZAAIgehpIAcAAIARBGIAAAAIAThGIAbAAIATBGIAAAAIARhGIAbAAIgeBpgAB6A1IgrhFIAAAAIABBFIgZAAIAAhpIAdAAIArBEIABAAIgBhEIAYAAIAABpgAgXA1IgngxIgBAAIAAAxIgZAAIAAhpIAZAAIAAArIABAAIAmgrIAeAAIgtAwIAwA5gAm7A1IAAhpIAqAAIANABQAHABAFAEQAFACAEAGQADAFAAAIQAAAJgFAGQgEAFgJADIAAABQAFAAAEABQAEACADAEQADADABADQACAFAAAFQAAAJgDAFQgEAGgGAEQgFAEgHACQgHABgJAAgAmiAhIAVgBIAFgCQADgBACgDQACgDAAgEQgBgGgFgDQgFgCgHAAIgPAAgAmigKIAOAAQAHAAAEgDQAEgCAAgHQAAgFgEgCQgEgDgIAAIgNAAg");
	this.shape.setTransform(0.55,0.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// BG
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A2lFoQiVAAhqhqQhphpAAiVQAAiUBphpQBqhqCVAAMAtLAAAQCVAABqBqQBpBpAACUQAACVhpBpQhqBqiVAAg");
	this.shape_1.setTransform(-0.05,-0.05,0.36,0.36,0,0,0,-0.1,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BTN, new cjs.Rectangle(-65,-12.9,130,25.9), null);


(lib.BGanimation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E5C554").s().p("A0ZCgIAAk/MAozAAAIAAE/g");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BGanimation, new cjs.Rectangle(-130.5,-16,261.1,32.1), null);


(lib.copyAnimations = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_95 = function() {
		this.stop()
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(95).call(this.frame_95).wait(1));

	// mask_idn (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A/PD0IAAnnMA+fAAAIAAHng");
	mask.setTransform(150.35,521.05);

	// thrills
	this.instance = new lib.thrills();
	this.instance.setTransform(150.1,448.15,1,0.0089);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleY:1,y:505.85},15,cjs.Ease.circOut).to({y:494.7},29,cjs.Ease.circOut).wait(43).to({scaleX:1.35,scaleY:1.35,x:150.05,y:484,alpha:0},6,cjs.Ease.circOut).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.6,496.6,400,48.89999999999998);


// stage content:
(lib._652252offer300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [130];
	// timeline functions:
	this.frame_130 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(130).call(this.frame_130).wait(1));

	// Brdr
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCCCCC").ss(1,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(125));

	// UOlogo
	this.instance = new lib.UOlogo();
	this.instance.setTransform(97,389);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).wait(125));

	// offer
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").p("ARyAAMgjjAAA");
	this.shape_1.setTransform(151.725,531.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABBE+IgDgBIABgJIACAAIACAAIADAAIACgBIADgGIACgFIgTgtIAMAAIANAhIAAAAIALghIALAAIgXA8IgEAEIgEACIgHABgAgOE+IAAhDIAKAAIAAAHIABAAIACgDIADgCIAEgCIAGgBQAEAAAEACIAHAFIAEAHQACAFAAAEQAAAFgCAFQgBAEgDADIgHAFQgEACgFAAQgFAAgDgCQgDgCgDgDIAAAAIAAAcgAADEFIgDADIgDAEIAAAGIAAAFIADAEIADAEIAGABIAFgBIAFgEIACgEIABgGIgBgFIgCgEIgFgEIgFgBQgDAAgDACgAhHE+IAAhDIALAAIAAAHIAAAAIACgDIADgCIAFgCIAGgBQAEAAAEACIAHAFIAEAHQACAFAAAEQAAAFgBAFQgCAEgDADIgHAFQgEACgFAAQgEAAgEgCQgFgCgBgDIgBAAIAAAcgAg0EFIgFADIgCAEIgBAGIABAFIACAEIAFAEIAFABIAGgBIADgEIADgEIABgGIgBgFIgDgEIgDgEIgGgBQgDAAgCACgAGbEnQgEgCgCgDQgEgDgBgEQgCgFABgFIABgJQABgEAEgDIAGgFQAEgCAFAAIAGABIADACIAEACIACACIAAgfIALAAIAABGIgLAAIAAgHQgCAEgEACQgEACgFAAQgFAAgEgCgAGhEEIgEAEIgDAEIgBAFIABAGIADAEIAEAEIAGABIAFgBIAEgEIADgEIAAgFIAAgGIgDgEIgEgDQgDgCgCAAIgGABgAFqEnQgFgBgCgDQgEgDgCgEQgCgFAAgFQAAgFACgFQACgEAEgDIAHgFQAEgCAFAAQAEAAAFACQADABAEADIAEAIQACAEgBAGIAAADIgiAAIACAFIADADIADACIAFABQAEAAAEgCIAEgEIAHAGQgGAJgMAAQgGAAgEgCgAFrEFQgEAEgBAEIAYAAIgBgEIgCgDIgEgDIgEAAQgFAAgDACgAiyEnQgGgCgCgDIAHgHIAEAEQADABAEAAIACAAIADgBIACgBIAAgDQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBgBIgHgCIgFgCIgEgCIgDgDIgBgGQAAgDABgDIAFgEQACgCADgBIAGgBQAFAAAFACQAEACADADIgHAGIgEgDIgGgBIgFABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAHACIAGACIAEACIAEAEQABACAAADQAAAEgBADIgFAFIgFACIgHABQgGAAgEgCgAkUEnQgEgBgDgEIgGgHQgCgEAAgGQAAgFACgEIAGgHIAHgFQAFgCAFAAQAEAAAFACQAFACADADQADADACAEQACAEAAAFQAAAGgCAEQgCAEgDADQgDAEgFABQgFACgEAAQgFAAgFgCgAkQEEIgEAEIgCAEIgBAFIABAGIACAEIAEAEIAGABIAGgBIADgEIACgEIABgGIgBgFIgCgEIgDgEIgGgBIgGABgAl0EnQgFgBgDgDIgFgHQgCgFAAgFQAAgGACgEIAFgHIAHgFIAJgCQAFAAAFACQAFACACACIAAgFIAIAAIAAgMIALAAIAAAMIAKAAIAAAJIgKAAIAAAVIAAAFQABAAAAABQABAAAAAAQABAAAAABQABAAABAAIADAAIACgBIAAAIIgDABIgEABQgEAAgDgCIgFgDIgCgFIAAgGIAAgVIgIAAIAAgCIgHAGIgEgDQgDgCgDAAQgCAAgCACIgFADIgBAFIgBAFIABAFIABAEIAFAEIAFABIAGgBIADgDIAHAHQgCADgFABQgEACgFAAQgFAAgEgCgAn5EnQgFgCgDgDIAHgHIAFAEQADABAEAAIACAAIACgBIACgBIAAgDQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBgBIgIgCIgEgCIgFgCIgCgDIgBgGQgBgDACgDIAEgEQADgCACgBIAHgBQAFAAAFACQAEACADADIgHAGIgFgDIgFgBIgFABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIAHACIAFACIAFACIADAEQACACAAADQAAAEgCADIgEAFIgGACIgHABQgFAAgFgCgAojEnQgFgBgDgDQgDgDgCgEQgCgFAAgFQAAgFACgFQACgEADgDIAHgFQAEgCAGAAQAEAAAEACQAEABADADIAFAIQABAEAAAGIAAADIgiAAIABAFIADADIAEACIAFABQAEAAADgCIAEgEIAIAGQgGAJgNAAQgFAAgEgCgAojEFQgDAEgBAEIAXAAIgBgEIgBgDIgEgDIgEAAQgGAAgDACgAJGEoIgFgCIgEgEQgBgDgBgEQAAgFADgDQADgDAEgBIAKgCIALgBIAAgBQAAgEgDgCQgDgCgEAAIgHABIgFAEIgGgHQAEgDAEgCIAKgCQAGAAAFACQADACACACIAEAGIABAHIAAAbIgLAAIAAgGQgCADgDACQgEACgFAAIgGgBgAJMEVIgEACQAAAAgBABQAAAAAAAAQAAABAAABQgBAAAAABIABADIACABIADABIACAAQAGAAADgDQADgDAAgFIAAgBIgIAAIgGABgAHoEoIgGgCIgEgEQgBgDAAgEQAAgFADgDQACgDAFgBIAKgCIAKgBIAAgBQAAgEgDgCQgDgCgEAAIgHABIgGAEIgFgHQAEgDAFgCIAKgCQAFAAAEACQAFACACACIADAGIAAAHIAAAbIgKAAIAAgGQgCADgEACQgDACgFAAIgFgBgAHtEVIgEACQAAAAgBABQAAAAAAAAQAAABAAABQAAAAAAABIABADIABABIACABIAEAAQAFAAADgDQADgDAAgFIAAgBIgIAAIgGABgAFIEnIgDgDIgDgFIgBgGIAAgVIgHAAIAAgJIAHAAIAAgMIAMAAIAAAMIALAAIAAAJIgLAAIAAAVIABAFQAAAAAAABQABAAAAAAQABAAAAABQABAAABAAIACAAIADgBIABAIIgEABIgEABQgFAAgDgCgAhwEoIgGgCIgEgEQgBgDAAgEQAAgFADgDQADgDAEgBIAKgCIAKgBIAAgBQAAgEgCgCQgEgCgEAAIgHABIgFAEIgGgHQAEgDAFgCIAKgCQAGAAAEACQAEACACACIADAGIABAHIAAAbIgLAAIAAgGQgCADgDACQgDACgFAAIgGgBgAhqEVIgFACQAAAAAAABQAAAAgBAAQAAABAAABQAAAAAAABIABADIABABIADABIADAAQAGAAADgDQACgDAAgFIAAgBIgIAAIgFABgAnMEnIgEgDIgCgFIgBgGIAAgVIgHAAIAAgJIAHAAIAAgMIALAAIAAAMIALAAIAAAJIgLAAIAAAVIABAFQAAAAABABQAAAAABAAQAAAAABABQABAAAAAAIADAAIACgBIABAIIgDABIgFABQgEAAgDgCgAKgEoIgCgCIgBgCIgBgDQAAgDACgCQACgCAEAAQADAAABACQADACAAADQAAADgDACQgBACgDAAIgEAAgABtEoIgCgCIgCgCIgBgDQABgDACgCQACgCADAAQADAAACACQACACABADQgBADgCACQgCACgDAAIgDAAgAKIEoIAAhGIALAAIAABGgAJxEoIAAgtIAKAAIAAAtgAIdEoIgSgtIAMAAIALAhIAAAAIAMghIAMAAIgSAtgAEqEoIAAgtIALAAIAAAtgAETEoIAAgZIAAgEIgBgEIgDgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABIgEACIgCAEIAAAFIAAAYIgLAAIAAgbQAAgEgCgDQgCgDgEAAIgEABIgEADIgBAEIgBAEIAAAZIgLAAIAAgtIALAAIAAAIIAAAAIACgEIADgCIAEgCIAEgBQAGAAADACQADADACAEQACgEAFgDQADgCAFAAQAEAAADACIAFAEIADAFIABAHIAAAcgADCEoIAAgtIALAAIAAAtgACUEoIAAhCIAMAAIAAA3IAcAAIAAALgAAqEoIAAhGIALAAIAABGgAjLEoIAAgZIgBgEIgBgEIgDgCQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgFABIgDADIgBAEIgBAEIAAAZIgLAAIAAgtIAKAAIAAAIIABAAQABgEADgCQAEgDAFAAQAEAAADACIAGAEIACAFIABAHIAAAcgAk3EoIAAgtIALAAIAAAtgAmXEoIAAgtIALAAIAAAtgAm3EoIAAgtIALAAIAAAIIAAAAQACgEADgCQAEgDAEAAIADAAIAAALIgDgBIgBAAQgDAAgDACQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABIgBAEIgBADIAAAYgApFEoIgPgcIgIAAIAAAcIgMAAIAAhCIAXAAIAJABQAEABADADQAEACACADQACAEAAAFQAAAHgEAFQgEAEgHACIASAdgApcEDIAJAAIAFgBIAFgBIADgDQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgDgDIgEgBIgEgBIgLAAgAJxDxQgCgCAAgDQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQABgCAEAAQADAAACACQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAADgCACQgCACgDAAQgEAAgBgCgAEqDxQgCgCAAgDQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQACgCACAAQAEAAACACQAAAAABABQAAAAABABQAAAAAAABQAAABAAAAQAAADgCACQgCACgEAAQgCAAgCgCgADCDxQgBgCgBgDQAAAAABgBQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCADAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQgBADgCACQgCACgDAAQgDAAgCgCgAk3DxQgCgCABgDQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCADAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAADgCACQgCACgDAAQgDAAgCgCgAmXDxQgBgCgBgDQAAAAABgBQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCADAAQAEAAABACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAADgDACQgBACgEAAQgDAAgCgCgAF0DAIgCgBIABgJIABAAIACAAIAEAAIACgBIACgGIACgFIgTgtIANAAIAMAhIAAAAIALghIAMAAIgXA8IgEAEIgEACIgHABgAgEDAIgDgBIABgJIACAAIABAAIADAAIACgBIACgGIACgFIgSgtIAMAAIAMAhIAAAAIALghIAMAAIgXA8IgEAEIgFACIgFABgAkTC+IgGgCIgEgDIAGgJQADADAEACIAIABIAHgBIAEgDIADgFIABgGIAAgDQgDADgEACQgDABgFAAQgFAAgEgBIgHgFQgDgDgBgFQgCgEAAgFIACgJQABgEADgDQACgDAFgCQAEgCAEAAQAFAAAEACQAEACADAEIAAgHIALAAIAAApQgBAGgBAFQgBAEgEAEQgDADgEACQgFACgHAAgAkLCGIgFADIgCAFIgBAFIABAFIACAFIAFADIAFABIAFgBIAEgDQADgCAAgCIABgGIgBgFQAAgDgDgCIgEgDIgFgBIgFABgALtC1IAHgYIALAAIgIAYgANeCpQgEgCgDgFQgEgEgBgHQgCgGABgIQgBgIACgGQABgHAEgEQADgEAEgDQAEgCAFAAQAGAAAFACQAEADADAEQACAEACAHQABAGABAIQgBAIgBAGQgCAHgCAEQgDAFgEACQgFACgGAAQgFAAgEgCgANiBzIgEAGIgCAIIAAAIIAAAIIACAIIAEAGQACADADAAQAFAAABgDQADgCACgEIABgIIABgIIgBgIIgBgIQgCgEgDgCQgBgDgFAAQgDAAgCADgALICqQgEgBgDgDQgEgCgCgEQgBgEAAgFIABgGIADgEIADgEIAFgCQgFgBgCgEQgDgDAAgGQAAgEACgEIAEgFQADgDAEgBIAIgBQAEAAAEABQAEABACADQADACACADQABADAAAEQAAAGgCAEQgEAEgEABIAFADIAEADIACAFIABAFQAAAFgBAEQgCAEgEACIgGAEIgJABIgJgBgALMCNIgDACIgDAEIgBAEQABAFADADQACADAGAAQAEAAAEgDQADgDAAgFIgBgEIgCgEIgEgCIgEgBIgFABgALKByQgDADAAAEQAAAEADADQADADAEAAIADgBIADgCIADgDIAAgEIAAgEIgDgDIgDgBIgDgBQgEAAgDACgAI8CpQgFgBgDgDIgFgHQgCgFAAgFQAAgGACgEIAFgHIAHgFIAJgCQAFAAAFACQAFACACADIgHAHIgEgDQgDgCgDAAQgCAAgCACIgFADIgBAFIgBAFIABAFIABAEIAFAEIAFABIAGgBIADgDIAHAHQgCADgFABQgEACgFAAQgFAAgEgCgAIICpQgEgBgDgDQgEgDgCgEQgBgFAAgFQAAgFABgFQACgEAEgDIAGgFQAFgCAFAAQAEAAAEACQAFABACADIAFAIQABAEABAGIAAADIgiAAIABAFIACADIAFACIAEABQAEAAADgCIAFgEIAIAGQgHAJgNAAQgFAAgEgCgAIICHQgDAEAAAEIAXAAIgCgEIgBgDIgDgDIgFAAQgFAAgEACgAFNCpQgEgCgCgEIAAAHIgLAAIAAhGIALAAIAAAfIACgCIAEgCIAEgCIAFgBQAEAAAFACIAGAFQAEADABAEIABAJQAAAFgBAFQgBAEgEADQgCADgEACQgEACgFAAQgFAAgEgCgAFOCHIgEADIgDAEIAAAGIAAAFIADAEIAEAEIAFABIAGgBIAEgEIADgEIABgGIgBgFIgDgEIgEgEIgGgBQgDAAgCACgADKCpQgDgBgEgEIgFgHQgCgEAAgGQAAgFACgEIAFgHIAHgFQAFgCAFAAQAFAAAEACQAFACADADQAEADACAEQABAEAAAFQAAAGgBAEQgCAEgEADQgDAEgFABQgEACgFAAQgFAAgFgCgADPCGIgFAEIgCAEIAAAFIAAAGIACAEIAFAEIAFABIAGgBIAEgEIACgEIABgGIgBgFIgCgEIgEgEIgGgBIgFABgACTCpQgDgBgEgEIgFgHQgCgEAAgGQAAgFACgEIAFgHIAHgFQAFgCAFAAQAFAAAEACQAFACADADQADADADAEQABAEAAAFQAAAGgBAEQgDAEgDADQgDAEgFABQgEACgFAAQgFAAgFgCgACXCGIgEAEIgCAEIAAAFIAAAGIACAEIAEAEIAGABIAGgBIAEgEIACgEIABgGIgBgFIgCgEIgEgEIgGgBIgGABgAh5CpQgFgCgDgDIAHgHIAGAEQADABADAAIADAAIACgBIABgBIABgDQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgIgCIgFgCIgEgCIgDgDIgBgGQAAgDACgDIADgEQADgCADgBIAGgBQAGAAAEACQAEACADADIgHAGIgEgDIgGgBIgEABQgBAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABABAAIAHACIAEACIAGACIACAEQACACAAADQAAAEgCADIgDAFIgHACIgHABQgFAAgFgCgAp0CpQgEgBgEgEIgFgHQgCgEAAgGQAAgFACgEIAFgHIAIgFQAEgCAFAAQAFAAAFACQAEACADADQADADACAEQACAEAAAFQAAAGgCAEQgCAEgDADQgDAEgEABQgFACgFAAQgFAAgEgCgApxCGIgDAEIgDAEIgBAFIABAGIADAEIADAEIAGABIAGgBIAEgEIACgEIABgGIgBgFIgCgEIgEgEIgGgBIgGABgArFCpQgEgCgDgDQgCgDgCgEQgCgFAAgFIACgJQACgEACgDIAIgFQAEgCAEAAIAFABIAFACIACACIADACIAAgfIALAAIAABGIgLAAIAAgHQgCAEgEACQgEACgFAAQgFAAgEgCgAq/CGIgEAEIgCAEIgBAFIABAGIACAEIAEAEIAFABIAGgBIAEgEIACgEIABgFIgBgGIgCgEIgEgDQgDgCgDAAIgFABgAr3CpQgEgBgDgDQgEgDgBgEQgCgFAAgFQAAgFACgFQABgEAEgDIAHgFQAFgCAEAAQAFAAAEACQAEABADADIAEAIQACAEAAAGIAAADIgiAAIABAFIADADIAEACIAEABQAFAAADgCIAFgEIAHAGQgHAJgMAAQgFAAgFgCgAr2CHQgDAEgBAEIAXAAIgBgEIgCgDIgDgDIgFAAQgEAAgEACgAsnCpQgFgCgDgDIAHgHIAFAEQADABADAAIADAAIADgBIABgBIABgDQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBIgHgCIgGgCIgDgCIgEgDIgBgGQABgDABgDIAEgEQADgCACgBIAHgBQAFAAAEACQAFACADADIgIAGIgDgDIgHgBIgEABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIAHACIAFACIAFACIADAEQABACABADQgBAEgBADIgEAFIgGACIgHABQgFAAgFgCgAgvCqIgFgCIgEgEQgBgDgBgEQAAgFADgDQADgDAEgBIAKgCIALgBIAAgBQAAgEgDgCQgDgCgEAAIgHABIgFAEIgGgHQAEgDAEgCIAKgCQAGAAAFACQADACACACIAEAGIABAHIAAAbIgLAAIAAgGQgCADgDACQgEACgFAAIgGgBgAgpCXIgEACQAAAAgBABQAAAAAAAAQAAABAAABQgBAAAAABIABADIACABIADABIACAAQAGAAADgDQADgDAAgFIAAgBIgIAAIgGABgAhMCpIgDgDIgDgFIgBgGIAAgVIgHAAIAAgJIAHAAIAAgMIAMAAIAAAMIALAAIAAAJIgLAAIAAAVIABAFQAAAAAAABQABAAAAAAQABAAAAABQABAAABAAIACAAIADgBIABAIIgEABIgEABQgFAAgDgCgAinCpIgDgDIgDgFIgBgGIAAgVIgHAAIAAgJIAHAAIAAgMIALAAIAAAMIAMAAIAAAJIgMAAIAAAVIACAFQAAAAAAABQABAAAAAAQABAAAAABQABAAABAAIACAAIADgBIABAIIgEABIgEABQgFAAgDgCgAn4CqIgFgCIgFgEQgBgDAAgEQAAgFADgDQADgDAEgBIAKgCIALgBIAAgBQAAgEgEgCQgDgCgDAAIgHABIgGAEIgFgHQAEgDAEgCIAKgCQAGAAAEACQAEACACACIADAGIABAHIAAAbIgKAAIAAgGQgCADgEACQgEACgFAAIgFgBgAnyCXIgEACQgBAAAAABQAAAAgBAAQAAABAAABQAAAAAAABIABADIACABIACABIADAAQAFAAADgDQAEgDAAgFIAAgBIgIAAIgGABgAtTCqIgGgCIgEgEQgBgDAAgEQAAgFACgDQADgDAFgBIAKgCIAKgBIAAgBQAAgEgDgCQgDgCgEAAIgHABIgFAEIgGgHQAEgDAFgCIAJgCQAGAAAEACQAEACADACIACAGIABAHIAAAbIgKAAIAAgGQgCADgEACQgDACgFAAIgFgBgAtNCXIgFACQAAAAgBABQAAAAAAAAQAAABAAABQAAAAAAABIABADIABABIACABIAEAAQAFAAADgDQADgDAAgFIAAgBIgIAAIgFABgAP5CqIgDgCIgCgCIAAgDQAAgDACgCQACgCAEAAQACAAACACQADACAAADQAAADgDACQgCACgCAAIgDAAgAJeCqIgCgCIgDgCIAAgDQAAgDADgCQACgCACAAQADAAADACQACACAAADQAAADgCACQgDACgDAAIgCAAgAAnCqIgCgCIgDgCIAAgDQAAgDADgCQACgCACAAQADAAADACQACACAAADQAAADgCACQgDACgDAAIgCAAgAO/CqIAAgKIAZgZIAFgGQACgDAAgEQAAgFgEgCQgDgDgEAAQgEAAgDADQgDADgBAFIgLgBIACgIIAGgGIAGgEQAEgBAFAAIAHABQAFABACADIAGAGQABADAAAFIAAAGIgDAFIgDAEIgXAXIAdAAIAAAKgAOICqIAAgKIAagZIAEgGQACgDAAgEQAAgFgDgCQgDgDgFAAQgEAAgDADQgDADgBAFIgKgBIACgIIAFgGIAHgEQAEgBAEAAIAIABQAEABADADIAFAGQABADABAFIgBAGIgCAFIgEAEIgWAXIAdAAIAAAKgAMbCqIAAgKIAZgZIAFgGQABgDAAgEQAAgFgDgCQgDgDgEAAQgFAAgDADQgCADgBAFIgKgBIABgIIAGgGIAGgEQAEgBAEAAIAIABQAFABADADIAFAGQABADAAAFIAAAGIgDAFIgDAEIgXAXIAeAAIAAAKgAKXCqIAAg0IgMALIgHgIIAUgRIALAAIAABCgAG4CqIAAhCIAXAAQAHAAAGACQAGACAGAEQAFADADAHQADAGAAAJQAAAJgDAGQgDAGgFAEQgGAEgGACQgGACgHAAgAHECgIAKAAIAJgBQAEgBAEgDQADgDACgEQADgEAAgHQAAgHgDgEQgCgFgDgCQgEgDgEgBIgJgBIgKAAgAESCqIgSgXIAAAXIgKAAIAAhGIAKAAIAAAsIARgTIAPAAIgUAUIAVAZgABOCqIAAhCIAaAAIAIABIAGADIAEAFQACADAAAFQAAAFgDAEQgDAEgFABQAGABAEAEQAEAEAAAHQAAAFgCAEIgGAGIgHADIgKABgABbCgIAOAAIAGgCIADgDQABgCAAgDQAAgFgDgCQgEgCgHAAIgKAAgABbCDIAKAAQAGAAADgCQACgDAAgEQAAgEgCgCQgDgCgHAAIgJAAgAjFCqIAAgZIAAgEIgCgDIgCgDIgEgBIgFABIgDACIgCAEIAAAFIAAAYIgMAAIAAhGIAMAAIAAAgIACgDIACgCIAEgCIAFgBQAEAAADACQAEABABADIADAFIABAHIAAAcgAkyCqIAAgtIALAAIAAAtgAlICqIAAgZIgBgEIgBgEIgCgCQgBgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgEABIgEADIgCAEIAAAEIAAAZIgLAAIAAgtIAKAAIAAAIIABAAQABgEADgCQAEgDAFAAQAEAAADACIAGAEIACAFIABAHIAAAcgAmgCqIAAgOIgeAAIAAgKIAcgqIAOAAIAAArIAJAAIAAAJIgJAAIAAAOgAmyCTIASAAIAAgegAosCqIAAgZIAAgEIgBgEIgDgCQAAgBgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgFABIgDADIgCAEIgBAEIAAAZIgLAAIAAgtIALAAIAAAIIAAAAQABgEAEgCQAEgDAEAAQAFAAADACIAFAEIADAFIABAHIAAAcgAuVCqIAAhCIAZAAIAIABIAGADIAFAFQACADAAAFQAAAFgEAEQgCAEgGABQAGABAFAEQADAEAAAHQAAAFgBAEIgHAGIgHADIgKABgAuJCgIAPAAIAFgCIAEgDQABgCAAgDQAAgFgEgCQgDgCgIAAIgKAAgAuJCDIAKAAQAGAAADgCQADgDAAgEQAAgEgDgCQgDgCgHAAIgJAAgAmGCYIAAgKIAXAAIAAAKgAuvCBIgIALIgGgFIAHgKIgMgEIADgIIAMAFIAAgOIAIAAIAAAOIAMgEIADAHIgNAEIAIALIgGAEgAkyBzQgCgCAAgDQAAAAABgBQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCADAAQAEAAACACQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAADgCACQgCACgEAAQgDAAgCgCgABOgGIAAi/IgxAiIguhIIBohDIBcAAIAAEogAj+gGIBIhdIgEAAQgUAAgSgHQgSgGgPgNQgNgMgJgTQgJgSAAgYQAAgcALgVQAKgVASgOQASgPAXgHQAYgHAaAAQAaAAAXAHQAYAHASAOQARAOALAVQAKAVAAAcQAAAcgLAZQgLAYgPAVIhDBfgAi1jdQgJAJAAANQAAANAJAIQAJAJAOAAQANAAAJgJQAJgIgBgNQABgNgJgJQgJgIgNAAQgOAAgJAIgAJ5gVQgKgEgHgIIAPgNQAEAGAHADQAGADAHAAIAHgBIAHgDQADgCABgDQADgDAAgEQAAgFgDgDQgBgDgEgCIgIgEIgUgHQgGgCgDgEQgEgDgDgFQgCgGAAgIQgBgIAEgGQAEgHAFgEQAGgEAIgCQAHgCAHAAQAJAAAIADQAKADAGAGIgNAPQgDgEgGgDQgGgDgGAAIgHABIgGADQgDABgCADQgBADAAAEQgBAEACADIAFAEIAGAEIAUAHQAGACAFADQAEAEAEAGQADAFAAAIQAAAJgDAHQgEAHgFAEQgGAFgIACQgHACgIAAQgLAAgLgEgAIigUQgIgDgGgGQgHgFgDgJQgDgIAAgKIAAhHIAUAAIAABGIABAKIAEAJQADADAFADQAFACAHAAQAHAAAFgCQAEgDADgDQAEgEABgFIABgKIAAhGIAUAAIAABHQAAAKgDAIQgEAJgGAFQgGAGgIADQgJADgJAAQgKAAgIgDgAPegUIgbgsIgbAsIgmAAIgLgZIgwAAIgKAZIgWAAIAxhwIARAAIAtBoIAhg0Igjg0IAYAAIAXAnIAXgnIAXAAIgiA1IAoA7gANOg+IAiAAIgQgugAL5gUIAAheIgiAAIAAgSIBYAAIAAASIgiAAIAABegAHAgUIAAhwIAUAAIAABfIAwAAIAAARgAFogUIAAhwIAkAAQAJAAAIACQAIACAGAEQAFAEADAGQADAGAAAJQAAAJgDAGQgEAHgGAEQgFADgJACQgHACgKAAIgOAAIAAAugAF8hTIAWgBQAFAAADgCQAEgCACgDQACgDAAgFQAAgFgCgDQgCgDgEgCIgIgCIgWgBgArpgaQgMgFgJgIQgIgJgFgLQgFgMAAgOQAAgPAFgLQAFgMAIgIQAJgJAMgEQAMgFAOAAQAOAAAMAFQAMAEAJAJQAJAIAEAMQAGALAAAPQAAAOgGAMQgEALgJAJQgJAIgMAFQgMAFgOAAQgOAAgMgFgArgh+QgHADgGAGQgFAGgEAIQgDAIAAAKQAAAKADAIQAEAIAFAGQAFAGAJADQAHADAJAAQAJAAAIgDQAIgDAGgGQAFgGADgIQADgIAAgKQAAgKgDgIQgDgIgFgGQgGgGgIgDQgIgEgJAAQgKAAgHAEgAoSgYIAAhiIAAAAIgmBiIgOAAIgkhiIgBAAIAABiIgVAAIAAh6IAiAAIAgBXIAAAAIAfhXIAiAAIAAB6gAstgYIgdg0IgPAAIAAA0IgVAAIAAh6IAqAAQAIAAAIACQAIACAGAEQAGAEAEAHQAEAHAAAJQAAANgHAJQgIAIgNADIAhA2gAtZhdIARAAIAKgBQAEgBAEgCQAEgBACgEQADgDgBgGQAAgFgBgDIgGgFQgDgCgFgBIgcAAgAvJgYIAAh6IBNAAIAAATIg4AAIAAAiIA1AAIAAASIg1AAIAAAzgAmHiFIAAgQQgPgBgNgFQgOgGgKgIIAfggIANAJIAJADIAJACQAFAAADgCQADgBAAgEQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAgBIgDgDIgkgNQgHgDgFgFQgFgFgDgHQgEgHAAgJQAAgLAEgJQADgIAHgGQAGgGAIgEQAJgDAIgCIAAgPIAWAAIAAAPQAOAAANAGQAOAFAKAKIgfAeQgEgGgHgDQgIgDgGAAQgGAAgDABQgDACAAADQAAAEADABIAcAKQAJADAHAGQAIAFAEAHQAGAIgBALQAAAMgDAJQgFAJgHAGQgHAGgIAEQgKADgKABIAAAQgAo8jCQgKgEgIgIIAQgPQAEAGAHAEQAIAEAHAAIAIgBQAEgBADgDQADgCACgDQACgEAAgEQAAgFgCgDQgDgEgDgCIgJgEIgVgIIgKgGQgFgEgCgGQgDgFAAgJQAAgJADgHQAFgHAFgEQAHgEAIgCQAHgDAJAAQAJAAAKAEQAJADAHAGIgOAQQgDgFgGgDQgHgDgGAAIgHABIgHADIgGAFQgCAEAAAEQABAEABADIAFAFIAHAEIAWAHQAGACAFAEQAFAEADAGQAEAGAAAJQAAAKgEAHQgDAHgGAFQgGAFgIACQgIADgJAAQgMAAgMgFgAtEjCQgNgFgIgIQgJgJgEgLQgGgMAAgOQAAgPAGgLQAEgMAJgIQAIgJANgEQALgFAOAAQAOAAAMAFQAMAEAKAJQAIAIAFAMQAFALAAAPQAAAOgFAMQgFALgIAJQgKAIgMAFQgMAFgOAAQgOAAgLgFgAs7kmQgIADgGAGQgFAGgDAIQgDAIAAAKQAAAKADAIQADAIAFAGQAGAGAIADQAIADAIAAQAKAAAHgDQAJgDAFgGQAGgGADgIQACgIAAgKQAAgKgCgIQgDgIgGgGQgFgGgJgDQgHgEgKAAQgJAAgHAEgAvPjCQgMgFgIgIQgJgJgFgLQgFgMAAgOQAAgPAFgLQAFgMAJgIQAIgJAMgEQAMgFAOAAQAOAAAMAFQAMAEAJAJQAIAIAGAMQAEALAAAPQAAAOgEAMQgGALgIAJQgJAIgMAFQgMAFgOAAQgOAAgMgFgAvGkmQgHADgGAGQgFAGgDAIQgDAIgBAKQABAKADAIQADAIAFAGQAGAGAHADQAIADAJAAQAJAAAIgDQAIgDAFgGQAGgGADgIQADgIAAgKQAAgKgDgIQgDgIgGgGQgFgGgIgDQgIgEgJAAQgKAAgHAEgApujAIAAhiIAAAAIglBiIgPAAIgkhiIAAAAIAABiIgVAAIAAh6IAhAAIAgBXIABAAIAfhXIAiAAIAAB6gAwTjAIgdg0IgPAAIAAA0IgWAAIAAh6IAqAAQAJAAAIACQAIACAGAEQAGAEAFAHQADAHAAAJQAAANgIAJQgGAIgNADIAgA2gAw/kFIASAAIAJgBQAFgBADgCQAEgBACgEQADgDAAgGQgBgFgCgDIgFgFQgDgCgFgBIgcAAgANJjGQgMgEgHgIQgJgIgEgLQgEgKAAgOQAAgNAEgLQAFgLAIgHQAIgIALgEQALgEANAAQANAAAMAEQALAEAGAGIgNAPQgEgFgIgDQgIgEgIAAQgJAAgHAEQgIADgFAFQgFAGgDAHQgDAIAAAIQAAAKADAHQADAHAFAGQAFAGAIADQAHADAKAAQAMAAAJgEIAAgdIgXAAIAAgQIArAAIAAA6QgJAEgKACQgKADgNAAQgOAAgLgFgAQgjEIAAhfIgjAAIAAgRIBZAAIAAARIgjAAIAABfgAPkjEIAAgyIg0AAIAAAyIgUAAIAAhwIAUAAIAAAtIA0AAIAAgtIAUAAIAABwgAMGjEIAAhwIAUAAIAABwgALcjEIg2hXIAABXIgTAAIAAhwIAaAAIA0BUIAAhUIAUAAIAABwgAJUjEIgagwIgOAAIAAAwIgUAAIAAhwIAnAAQAIAAAHACQAHABAGAEQAGAEAEAGQADAGAAAJQAAAMgHAIQgHAHgMADIAeAygAIskEIAQAAIAIgBIAIgCIAGgFQACgDAAgFQAAgFgCgDQgCgDgDgBQgDgCgFgBIgZAAgAHAjEIAAhwIBKAAIAAARIg2AAIAAAdIAzAAIAAAQIgzAAIAAAgIA5AAIAAASgAFojEIAAhwIAkAAQAJAAAIACQAIABAGAEQAFAEADAGQADAHAAAIQAAAKgDAGQgEAGgGAEQgFAEgJACQgHABgKAAIgOAAIAAAvgAF8kDIAWgBQAFgBADgCQAEgBACgEQACgDAAgFQAAgFgCgDQgCgDgEgCIgIgCIgWAAgADYkDIgHAJIgLgIIAGgJIgLgDIAFgNIALAEIAAgLIAOAAIAAALIAMgDIADAMIgKADIAHAJIgMAIg");
	this.shape_2.setTransform(148.6,525.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAAKIgFAIIgLgHIAGgIIgKgDIAFgLIAKAEIAAgKIALAAIAAAKIAKgDIAFAKIgKADIAGAIIgLAHg");
	this.shape_3.setTransform(538.2,507.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLBZIAAgQQgNgBgOgGQgNgFgKgIIAeggIAFAFIAIAFIAJADIAIABIAHgBQADgCAAgEIgBgDIgDgCIgIgEIgMgEIgOgGQgHgDgFgFQgFgEgDgGQgEgHAAgJQABgLAEgIQADgIAGgHQAHgFAIgEQAHgDAJgBIAAgQIAUAAIAAAPQANABAOAFQANAFAKAJIgeAeQgFgFgHgEQgHgDgGAAIgIABQgCACAAAEQgBADAEABIAJAFIARAFQAIADAHAFQAIAFAEAHQAGAHAAALQAAALgFAJQgEAJgHAGQgGAGgJAEQgJADgKABIAAAQg");
	this.shape_4.setTransform(472.4,513.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgBCaIAAjGIg0AkIgxhMIBthFIBgAAIAAEzg");
	this.shape_5.setTransform(519.025,520.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhjCfIBJhfIACgCIgFAAQgUAAgTgHQgTgGgPgNQgOgOgKgTQgIgSgBgZQAAgdAMgWQAKgWATgPQATgPAZgIQAYgHAaAAQAbAAAYAHQAZAIATAOQASAOALAXQALAVAAAeQAAAdgMAZQgLAagQAVIhGBjgAgXg/QgJAIAAAOQAAANAJAJQAJAJAOAAQAOAAAJgJQAJgJAAgNQAAgOgJgIQgJgKgOAAQgOAAgJAKg");
	this.shape_6.setTransform(494,520.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(2).p("AClAAIlJAA");
	this.shape_7.setTransform(594.8817,494.2441,0.7279,0.7279);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(2).p("AOwAAI9fAA");
	this.shape_8.setTransform(536.6323,542.9763,0.7279,0.7279);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(2).p("AClAAIlJAA");
	this.shape_9.setTransform(479.9115,494.2441,0.7279,0.7279);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAVAsIgVgjIgUAjIgTAAIAeguIgbgpIATAAIARAeIASgeIARAAIgaApIAfAug");
	this.shape_10.setTransform(594.225,522.575);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAbAsIgIgUIglAAIgIAUIgSAAIAmhXIANAAIAmBXgAANAKIgNgiIgNAiIAaAAg");
	this.shape_11.setTransform(586.275,522.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHAsIAAhJIgbAAIAAgOIBFAAIAAAOIgbAAIAABJg");
	this.shape_12.setTransform(578.875,522.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRArQgHgDgGgHIALgKQADAFAGACQAFADAFAAIAFgBIAFgCIAEgEIABgGQAAgDgBgDIgFgDIgGgEIgHgCIgIgDIgHgEQgDgDgCgEQgCgEAAgGQAAgHADgFQADgFAEgDQAEgDAHgBQAFgCAFAAQAHAAAGADQAHACAGAFIgKALQgDgDgEgDQgFgCgFAAIgEABIgFACIgEAEIgBAFIABAFIAEAEIAEADIAHACIAIACIAJAFQADACACAEQADAFAAAHQAAAHgDAEQgCAGgEAEQgFADgFACQgHABgFAAQgIAAgJgDg");
	this.shape_13.setTransform(569.5,522.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNArQgHgDgEgEQgFgFgDgGQgCgGAAgIIAAg3IAPAAIAAA2IABAIQABADADADQACADAEACQADACAFAAQAFAAAEgCQAEgCACgDQADgDABgDIABgIIAAg2IAPAAIAAA3QAAAIgDAGQgCAGgFAFQgFAEgGADQgHACgHAAQgHAAgGgCg");
	this.shape_14.setTransform(562.225,522.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaAsIAAhXIAQAAIAABJIAkAAIAAAOg");
	this.shape_15.setTransform(555.55,522.575);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeAsIAAhXIAdAAQAGAAAGACQAHABADADQAFADACAFQADAFAAAHQAAAHgDAFQgDAFgFACQgEADgGABIgMABIgMAAIAAAlgAgOgFIAKAAIAHAAIAGgCQADgCABgCQACgDAAgDQAAgEgCgDQgBgCgDgCIgGgBIgGgBIgLAAg");
	this.shape_16.setTransform(548.95,522.575);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgHAsIAAhJIgbAAIAAgOIBFAAIAAAOIgbAAIAABJg");
	this.shape_17.setTransform(602.275,509.875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAUAsIAAgnIgnAAIAAAnIgQAAIAAhXIAQAAIAAAkIAnAAIAAgkIAQAAIAABXg");
	this.shape_18.setTransform(594.675,509.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLArQgJgDgGgHQgGgGgEgIQgDgJgBgKQABgJADgJQAEgJAGgFQAHgHAIgCQAJgEAJAAQAKAAAJADQAJADAFAFIgLAMQgDgEgGgDQgGgCgHAAQgHAAgFACQgFADgEAEQgEAFgCAFQgCAGgBAGQABAHACAGQACAFAEAFQAEAEAGADQAFACAHAAQAKAAAIgDIAAgWIgTAAIAAgMIAhAAIAAAtIgOAEQgJACgJAAQgLAAgIgDg");
	this.shape_19.setTransform(585.65,509.85);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgHAsIAAhXIAPAAIAABXg");
	this.shape_20.setTransform(579.8,509.875);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AATAsIgphDIAABDIgQAAIAAhXIAVAAIAoBBIAAAAIAAhBIAQAAIAABXg");
	this.shape_21.setTransform(573.725,509.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAOAsIgTglIgLAAIAAAlIgQAAIAAhXIAfAAIALABQAFACAFADQAEADADAEQADAFAAAHQAAAKgFAGQgGAFgJACIAXAngAgQgFIAMAAIAGgBIAGgBQADgCABgCQACgDAAgEQAAgDgCgDIgDgDIgGgCIgFgBIgOAAg");
	this.shape_22.setTransform(563.25,509.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdAsIAAhXIA5AAIAAAOIgpAAIAAAWIAnAAIAAAMIgnAAIAAAZIArAAIAAAOg");
	this.shape_23.setTransform(555.875,509.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgeAsIAAhXIAcAAQAHAAAHACQAFABAFADQAEADADAFQACAFAAAHQAAAHgDAFQgCAFgFACQgFADgGABIgNABIgLAAIAAAlgAgOgFIALAAIAGAAIAGgCQADgCACgCQABgDAAgDQAAgEgBgDQgCgCgDgCIgGgBIgGgBIgLAAg");
	this.shape_24.setTransform(548.9,509.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgCAFIgBgBIgBgCIgBgCQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgCgBg");
	this.shape_25.setTransform(588.4,560.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgDAcIAAg2IAHAAIAAA2g");
	this.shape_26.setTransform(586.525,557.95);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgBABAAAAIgDgCg");
	this.shape_27.setTransform(584.625,558.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgGASIgFgCIgDgEIgBgEQAAgEACgDQACgBAEgBIAHgCIAIAAIAAgBQAAgDgDgCQgCgCgDABIgFABIgEACIgFgFIAIgEIAHgCQAEABADABQADABACADIACAEIABAFIAAAVIgIAAIAAgFIAAAAQgCACgDACQgDACgCgBIgEAAgAACACIgEAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABIABACIACAAIADAAQADAAACgCQADgCAAgEIAAgCIgCAAg");
	this.shape_28.setTransform(581.6,558.95);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgEASIgOgjIAKAAIAIAZIAAAAIAJgZIAKAAIgOAjg");
	this.shape_29.setTransform(577.875,558.95);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgGASIgFgCIgDgEIgBgEQAAgEACgDQACgBAEgBIAHgCIAIAAIAAgBQAAgDgDgCQgCgCgDABIgFABIgEACIgFgFIAIgEIAHgCQAEABADABQADABACADIACAEIABAFIAAAVIgIAAIAAgFIAAAAQgCACgDACQgDACgCgBIgEAAgAACACIgEAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABIABACIACAAIADAAQADAAACgCQADgCAAgEIAAgCIgCAAg");
	this.shape_30.setTransform(573.95,558.95);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgIAaIgFgDIgDgHIgCgGQAAgFACgDQABgCACgDQACgCAEgBQADgCADAAIAEABIACABIADACIACABIAAgYIAJAAIAAA2IgIAAIAAgFQgDADgDABIgGACQgEAAgDgCgAgDAAIgDACIgDADIAAAFIAAADIADAEIADADIADABIAEgBIADgDIADgEIABgDIgBgFIgDgDIgDgCIgEgBIgDABg");
	this.shape_31.setTransform(567.9,558);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgFASIgGgEQgDgDgBgDQgCgEAAgEQAAgDACgEIAEgFQACgDAEgBIAGgCIAHABIAFAFIAEAFIABAHIAAABIAAACIgaAAIABAEIACACIAEABIACABQADAAADgBIADgDIAGAEQgFAIgKgBIgGAAgAAJgCIAAgEIgCgDIgCgBIgEgBQgDAAgDACQgDADAAAEIARAAIAAAAg");
	this.shape_32.setTransform(563.675,558.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAGAXIgGgBIgCgDIgCgEIAAgEIAAgQIgHAAIAAgHIAHAAIAAgKIAHAAIAAAKIAJAAIAAAHIgJAAIAAAQIABADQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIACAAIABgBIABAHIgDABg");
	this.shape_33.setTransform(560.325,558.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQAAAAABAAQABABAAAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAQgBABAAAAIgDgCg");
	this.shape_34.setTransform(558.225,558.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AATASIAAgTIAAgCIgBgDIgDgDIgDgBIgDABIgDADIgBADIgBADIAAASIgIAAIAAgUQABgEgCgBQgCgDgDAAIgEABIgBADIgCADIAAADIAAASIgJAAIAAgiIAIAAIAAAFIACgCIACgCIADgBIAEgBQAEAAADACQABABACADQACgCACgCQAEgCADAAIAHABIADADIADAFIABAFIAAAVg");
	this.shape_35.setTransform(554.05,558.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAIgDgCg");
	this.shape_36.setTransform(549.925,558.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgPAaIAAgzIAKAAIAAArIAVAAIAAAIg");
	this.shape_37.setTransform(547.35,558.125);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgCAFIgBgBIgBgCIgBgCQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgCgBg");
	this.shape_38.setTransform(542.8,560.175);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgMAaIgDAAIABgIIACABIABAAIADgBIABgBIABgBIACgDIABgEIgPgiIAKAAIAJAZIAJgZIAJAAIgRApIgCAFIgCADIgDACIgFAAg");
	this.shape_39.setTransform(540.325,559.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgDAcIAAg2IAHAAIAAA2g");
	this.shape_40.setTransform(537.525,557.95);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgSAbIAAg0IAIAAIAAAFIABAAIABgCIADgCIADgBIAEgBIAHACIAFAEQADACAAADQACAEAAAEIgCAHQAAACgDADIgFAEQgEABgEAAQgCAAgDgBIgFgEIAAAWgAgDgSIgEADIgCAEIgBAEIABAEIACADIAEACIADABIAFgBIACgCIACgDIABgEIgBgEIgCgEIgCgDIgFgBIgDABg");
	this.shape_41.setTransform(534.4,559.775);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgSAbIAAg0IAJAAIAAAFIAAAAIACgCIACgCIADgBIAEgBIAHACIAFAEQADACABADQABAEAAAEIgBAHQgBACgDADIgFAEQgEABgDAAQgDAAgDgBIgFgEIAAAWgAgEgSIgCADIgCAEIgBAEIABAEIACADIACACIAEABIAEgBIAEgCIACgDIAAgEIAAgEIgCgEIgEgDIgEgBIgEABg");
	this.shape_42.setTransform(529.85,559.775);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgHASIgEgCIgDgEIgBgEQAAgEACgDQACgBADgBIAIgCIAIAAIAAgBQAAgDgCgCQgDgCgDABIgEABIgFACIgEgFIAGgEIAHgCQAFABADABQADABACADIADAEIAAAFIAAAVIgIAAIAAgFIgBAAQgBACgCACQgEACgCgBIgFAAgAABACIgDAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQgBAAAAABIABABIACACIACAAIABAAQAEAAADgCQACgCAAgEIAAgCIgCAAg");
	this.shape_43.setTransform(525.4,558.95);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgHARQgEgCgCgCIAFgFIAEACIAEABIACAAIACAAIABgCIABgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAIgFgDIgEgBIgDgBIgDgCIgBgFIACgEIADgEIAFgCIAEgBQAEABADABQADABACADIgFAFIgEgDIgEgBIgDABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAAAABQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAIAFACIAEABIAEABIADACIAAAFIAAAFIgEAEIgFACIgFAAIgHgBg");
	this.shape_44.setTransform(520.1,558.95);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAHASIAAgTIAAgCIgBgDIgCgDIgDgBIgDABIgCADIgCADIAAADIAAASIgJAAIAAgiIAIAAIAAAFIAEgEQADgCADAAIAGABIAEADIACAFIABAFIAAAVg");
	this.shape_45.setTransform(516.475,558.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgGARQgDgBgDgCIgFgGQgBgEAAgEQAAgDABgEIAFgFQADgDADgBIAGgCQAEABAEABQADABADADIADAFQACAEAAADQAAAEgCAEIgDAGQgDACgDABQgEACgEgBIgGgBgAgDgJIgEACIgBAEIgBADIABAEIABAEIAEACIADABIAFgBIADgCIABgEIABgEIgBgDIgBgEIgDgCIgFgBIgDABg");
	this.shape_46.setTransform(512.15,558.95);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgBABAAAAIgDgCg");
	this.shape_47.setTransform(509.025,558.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAGAXIgGgBIgCgDIgCgEIAAgEIAAgQIgHAAIAAgHIAHAAIAAgKIAHAAIAAAKIAJAAIAAAHIgJAAIAAAQIABADQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIACAAIABgBIABAHIgDABg");
	this.shape_48.setTransform(506.775,558.475);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgDASIgGgEIgFgGQgBgEAAgEQAAgDABgEIAFgFIAGgEQADgBADgBQAEABADABQAEACACACIgGAFIgDgCIgEgBIgDABIgDACIgCAEIgBADIABAEIACAEIADACIADABIAFgBIACgCIAGAGQgCACgEACIgHAAIgGAAg");
	this.shape_49.setTransform(504.05,558.95);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAIgDgCg");
	this.shape_50.setTransform(501.225,558.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgKASIAAgiIAJAAIAAAGIAAAAQABgDACgCQADgCADAAIABAAIABAAIAAAIIgBAAIgBAAIgFABIgDADIAAACIgBADIAAASg");
	this.shape_51.setTransform(499.2,558.9);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AAGAXIgGgBIgCgDIgCgEIAAgEIAAgQIgHAAIAAgHIAHAAIAAgKIAHAAIAAAKIAJAAIAAAHIgJAAIAAAQIABADQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIACAAIABgBIABAHIgDABg");
	this.shape_52.setTransform(496.375,558.475);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgHARQgEgCgDgCIAGgFIAEACIAEABIACAAIACAAIACgCIAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBAAIgFgDIgEgBIgDgBIgCgCIgBgFIABgEIADgEIAFgCIADgBQAEABAEABQADABADADIgGAFIgDgDIgFgBIgCABQgBAAAAABQgBAAAAAAQAAABAAAAQgBAAAAABQAAABABAAQAAAAAAABQAAAAABAAQAAABABAAIAEACIAEABIAEABIACACIACAFIgCAFIgDAEIgEACIgGAAIgHgBg");
	this.shape_53.setTransform(493.6,558.95);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgFASIgGgEQgDgDgBgDQgCgEAAgEQAAgDACgEIAEgFQACgDAEgBIAGgCIAHABIAFAFIAEAFIABAHIAAABIAAACIgaAAIABAEIACACIAEABIACABQADAAADgBIADgDIAGAEQgFAIgKgBIgGAAgAAJgCIAAgEIgCgDIgCgBIgEgBQgDAAgDACQgDADAAAEIARAAIAAAAg");
	this.shape_54.setTransform(490.025,558.95);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAIAaIgLgWIgGAAIAAAWIgKAAIAAgzIASAAIAGABIAHACQADACABADQABADAAAEQAAAGgCADQgEADgFABIAOAXgAgJgDIAHAAIAEAAIADgBIACgCIABgEIgBgEIgCgCIgDgBIgDAAIgIAAg");
	this.shape_55.setTransform(485.9,558.125);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgCAFIgBgBIgCgCIAAgCQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgCgBg");
	this.shape_56.setTransform(604.55,551.725);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgFAaIgFgCIgFgEIgDgFIAJgDQABADACADQADACADAAIADgBIAEgBIACgDIAAgEIgBgEIgCgDIgFgBIgDgBIgCAAIAAgGIADAAIACAAIAEgBIADgDIAAgDIAAgEIgCgCIgDgBIgDgBQgCAAgCACQgCACgBADIgJgCIADgFIAEgEIAEgCIAFgBIAHABIAFADQADABABADQABADAAADQAAAEgCADQgDAEgEABQAFAAADADQACADAAAFQABAEgCADQgBADgEACIgFADIgHABIgFgBg");
	this.shape_57.setTransform(601.25,549.675);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAEAaIAAgoIgKAIIgFgGIAPgNIAIAAIAAAzg");
	this.shape_58.setTransform(596.5,549.675);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgEAbQgEgCgBgDIgBAAIAAAFIgIAAIAAg2IAJAAIAAAYIAAAAIACgBIACgCIADgBIAEgBQAEAAADACIAFADIAEAFIABAIIgBAGIgEAGIgFAFQgDABgEAAQgDAAgDgBgAgDAAIgEACIgCADIAAAFIAAADIACAEIAEADIADABIAEgBIADgDIACgEIABgDIgBgFIgCgDIgDgCIgEgBIgDABg");
	this.shape_59.setTransform(590.825,549.55);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgFARIgGgDQgDgCgBgEQgCgEAAgEQAAgDACgEIAEgFQACgDAEgBIAGgCIAHABIAFAFIAEAFIABAHIAAABIAAACIgaAAIABAEIACACIAEABIACABQADAAADgBIADgDIAGAEQgFAIgKgBIgGgBgAAJgCIAAgEIgCgDIgCgBIgEgBQgDAAgDACQgDADAAAEIARAAIAAAAg");
	this.shape_60.setTransform(586.375,550.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgQAaIAAgzIAhAAIAAAIIgXAAIAAAOIAVAAIAAAHIgVAAIAAAWg");
	this.shape_61.setTransform(582.725,549.675);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgMAaIgDAAIABgIIACABIABAAIADgBIABgBIABgBIACgDIABgEIgPgiIAKAAIAJAZIAJgZIAJAAIgRApIgCAFIgCADIgDACIgFAAg");
	this.shape_62.setTransform(576.925,551.375);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgEAbQgEgCgBgDIgBAAIAAAFIgIAAIAAg2IAJAAIAAAYIAAAAIACgBIACgCIADgBIAEgBQAEAAADACIAFADIAEAFIABAIIgBAGIgEAGIgFAFQgDABgEAAQgDAAgDgBgAgDAAIgEACIgCADIAAAFIAAADIACAEIAEADIADABIAEgBIADgDIACgEIABgDIgBgFIgCgDIgDgCIgEgBIgDABg");
	this.shape_63.setTransform(572.925,549.55);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AAGAbIgNgSIgBAAIAAASIgIAAIAAg2IAIAAIAAAjIABAAIAMgPIAMAAIgQAPIAQATg");
	this.shape_64.setTransform(567.05,549.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgGARQgEgBgDgCIgDgGQgCgEAAgEQAAgDACgEIADgFQADgDAEgBIAGgCQAEABADABQAEABACADIAFAFQABAEAAADQAAAEgBAEIgFAGQgCACgEABQgDACgEgBIgGgBgAgEgJIgCACIgCAEIgBADIABAEIACAEIACACIAEABIAEgBIAEgCIACgEIABgEIgBgDIgCgEIgEgCIgEgBIgEABg");
	this.shape_65.setTransform(562.6,550.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgGARQgEgBgDgCIgDgGQgCgEAAgEQAAgDACgEIADgFQADgDAEgBIAGgCQAEABAEABQADABACADIAFAFQABAEAAADQAAAEgBAEIgFAGQgCACgDABQgEACgEgBIgGgBgAgEgJIgCACIgCAEIgBADIABAEIACAEIACACIAEABIAEgBIAEgCIACgEIABgEIgBgDIgCgEIgEgCIgEgBIgEABg");
	this.shape_66.setTransform(558.2,550.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgSAaIAAgzIAUAAIAFABIAFACQACACACACQABADAAADQAAAFgDACQgCADgEABIAAABQAFAAADACQADAEAAAFQAAAEgBADQgCADgDABQgDACgDABIgHABgAgIASIAIAAIACAAIAEgBIADgDIABgEQAAgEgCgBQgEgCgEAAIgIAAgAgIgEIAIAAQADAAACgCQADgBAAgEQAAgDgDgCQgCgBgEAAIgHAAg");
	this.shape_67.setTransform(553.8,549.675);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgCAFIgBgBIgBgCIgBgCQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgCgBg");
	this.shape_68.setTransform(548.9,551.725);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgMAaIgDAAIABgIIACABIABAAIADgBIABgBIABgBIACgDIABgEIgPgiIAKAAIAJAZIAJgZIAJAAIgRApIgCAFIgCADIgDACIgFAAg");
	this.shape_69.setTransform(546.425,551.375);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AgGASIgFgCIgDgDIgBgFQAAgFACgCQACgBAEgBIAHgCIAIAAIAAgBQAAgDgDgCQgCgCgDABIgFABIgEACIgFgFIAIgEIAHgCQAEABADABQADABACADIACAEIABAFIAAAUIgIAAIAAgEIAAAAQgCACgDACQgDACgCgBIgEAAgAACACIgEAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABIABACIACAAIADAAQADAAACgCQADgCAAgEIAAgCIgCAAg");
	this.shape_70.setTransform(542.45,550.5);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AAGAXIgGgBIgCgDIgCgEIAAgEIAAgQIgHAAIAAgHIAHAAIAAgKIAHAAIAAAKIAJAAIAAAHIgJAAIAAAQIABADQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIACAAIABgBIABAHIgDABg");
	this.shape_71.setTransform(539.275,550.025);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AgHARQgEgCgDgCIAHgFIADACIAFABIABAAIACAAIABgCIABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgFgDIgEgBIgDgBIgDgCIgBgFIACgEIADgEIAEgCIAFgBQAEABADABQADABACADIgFAFIgEgDIgEgBIgDABQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABABAAQAAAAAAABQAAAAABAAQAAABAAAAIAFACIAEABIAEABIACACIABAFIgBAGIgDADIgFACIgFAAIgHgBg");
	this.shape_72.setTransform(536.5,550.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AAGAXIgGgBIgCgDIgCgEIAAgEIAAgQIgHAAIAAgHIAHAAIAAgKIAHAAIAAAKIAJAAIAAAHIgJAAIAAAQIABADQAAABAAAAQABAAAAAAQABABAAAAQABAAABAAIACAAIABgBIABAHIgDABg");
	this.shape_73.setTransform(531.925,550.025);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AAIAbIAAgTIgBgDIgBgDIgCgCIgDAAIgDAAIgDACIgBADIgBADIAAATIgIAAIAAg2IAIAAIAAAaIABAAIABgCIADgDIACgBIADgBIAGABIAEAEIADADIAAAGIAAAVg");
	this.shape_74.setTransform(528.7,549.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgFAaIgEgBIgFgCIgDgCIAEgHIAGAEQADABAEAAIAEgBIAEgCIABgEIABgFIAAgCQgCACgDABQgDACgCAAQgFAAgDgCQgDgBgCgDQgCgCgBgCIgCgHQAAgEACgDQABgEACgCIAFgEQADgCAFAAQACAAADACQADABACAEIAAgGIAJAAIAAAfQAAAFgBAEQgCADgCADIgGAEQgEACgEAAgAgDgSIgEADIgBADIgBAFIABAEIABADIAEACIADABIAEgBIAEgCIABgDIABgEIgBgFIgBgDIgEgDIgEgBIgDABg");
	this.shape_75.setTransform(524.2,551.325);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgDAaIAAgiIAHAAIAAAigAgDgQQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCQAAAAABAAQABAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQgBAAAAAAIgDgBg");
	this.shape_76.setTransform(521.075,549.65);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AAHASIAAgTIAAgDIgBgCIgCgDIgDgBIgDABIgCADIgCACIAAAEIAAASIgJAAIAAgiIAIAAIAAAFIAEgEQADgCADAAIAGABIAEADIACAFIABAFIAAAVg");
	this.shape_77.setTransform(518.025,550.45);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgIAEIAAgHIARAAIAAAHg");
	this.shape_78.setTransform(514.825,550.475);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AAEAaIAAgLIgXAAIAAgIIAVggIALAAIAAAhIAHAAIAAAHIgHAAIAAALgAgKAIIAOAAIAAgXIAAAAg");
	this.shape_79.setTransform(511.325,549.675);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgGASIgFgCIgDgDIgBgFQAAgFACgCQACgBAEgBIAHgCIAIAAIAAgBQAAgDgDgCQgCgCgDABIgEABIgFACIgEgFIAHgEIAHgCQAEABADABQADABACADIACAEIABAFIAAAUIgIAAIAAgEIgBAAQgBACgCACQgDACgDgBIgEAAgAACACIgEAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAAABIACACIABAAIACAAQAEAAACgCQADgCAAgEIAAgCIgCAAg");
	this.shape_80.setTransform(505.35,550.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AAHASIAAgTIAAgDIgBgCIgCgDIgDgBIgDABIgCADIgCACIAAAEIAAASIgJAAIAAgiIAIAAIAAAFIAEgEQADgCADAAIAGABIAEADIACAFIABAFIAAAVg");
	this.shape_81.setTransform(499.625,550.45);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgGARQgDgBgEgCIgDgGQgCgEAAgEQAAgDACgEIADgFQAEgDADgBIAGgCQAEABAEABQADABACADIAFAFQABAEAAADQAAAEgBAEIgFAGQgCACgDABQgEACgEgBIgGgBgAgEgJIgDACIgBAEIgBADIABAEIABAEIADACIAEABIAEgBIAEgCIACgEIABgEIgBgDIgCgEIgEgCIgEgBIgEABg");
	this.shape_82.setTransform(495.3,550.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AgIAbIgFgFIgEgGIgBgGQAAgEABgEQABgCADgDQACgCADgBQAEgCADAAIAEABIADABIACACIACABIAAgYIAJAAIAAA2IgJAAIAAgFQgCADgCACIgHABQgDAAgEgBgAgDAAIgEACIgCADIAAAFIAAADIACAEIAEADIADABIAFgBIACgDIACgEIABgDIgBgFIgCgDIgCgCIgFgBIgDABg");
	this.shape_83.setTransform(488.95,549.55);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgFARIgGgDQgDgCgBgEQgCgEAAgEQAAgDACgEIAEgFQACgDAEgBIAGgCIAHABIAFAFIAEAFIABAHIAAABIAAACIgaAAIABAEIACACIAEABIACABQADAAADgBIADgDIAGAEQgFAIgKgBIgGgBgAAJgCIAAgEIgCgDIgCgBIgEgBQgDAAgDACQgDADAAAEIARAAIAAAAg");
	this.shape_84.setTransform(484.725,550.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AgHARQgEgCgCgCIAGgFIADACIAFABIABAAIACAAIABgCIABgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAIgFgDIgEgBIgDgBIgDgCIgBgFIACgEIADgEIAEgCIAFgBQAEABADABQADABACADIgFAFIgEgDIgEgBIgDABQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAIAFACIAEABIAEABIACACIABAFIgBAGIgDADIgFACIgFAAIgHgBg");
	this.shape_85.setTransform(481.05,550.5);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgHASIgEgCIgDgDIgBgFQAAgFACgCQACgBADgBIAIgCIAIAAIAAgBQAAgDgCgCQgDgCgDABIgFABIgEACIgFgFIAHgEIAHgCQAFABADABQADABACADIADAEIAAAFIAAAUIgIAAIAAgEIAAAAQgBACgEACQgDACgCgBIgFAAgAABACIgDAAIgDADQAAAAgBAAQAAAAAAABQAAAAAAABQgBAAAAABIABABIABACIADAAIACAAQADAAADgCQACgCAAgEIAAgCIgCAAg");
	this.shape_86.setTransform(477.4,550.5);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AgSAaIAAgzIAUAAIAFABIAFACQACACABACQACADAAADQAAAFgCACQgDADgEABIAAABQAFAAADACQADAEAAAFQAAAEgCADQgBADgDABQgDACgDABIgHABgAgJASIAIAAIAEAAIADgBIADgDIABgEQAAgEgDgBQgDgCgEAAIgJAAgAgJgEIAIAAQAEAAADgCQACgBAAgEQAAgDgCgCQgDgBgFAAIgHAAg");
	this.shape_87.setTransform(473.3,549.675);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AAAAFIgFAJIgFgEIAGgIIgKgDIACgFIAKADIAAgKIAFAAIAAAKIAKgDIACAGIgKACIAGAIIgFAEg");
	this.shape_88.setTransform(469.225,548.525);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AAgAsIAAhGIgbBGIgKAAIgahGIAAAAIAABGIgPAAIAAhXIAYAAIAWA9IAXg9IAYAAIAABXg");
	this.shape_89.setTransform(572.775,494.225);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AgSArQgIgDgHgHQgGgGgDgIQgEgJAAgKQAAgJAEgJQADgJAGgFQAHgHAIgCQAIgEAKAAQAKAAAJAEQAIACAHAHQAGAFAEAJQADAJAAAJQAAAKgDAJQgEAIgGAGQgHAHgIADQgJADgKAAQgJAAgJgDgAgMgdQgFADgEAEQgEAFgCAFQgCAGAAAGQAAAHACAGQACAFAEAFQAEAEAGADQAFACAGAAQAGAAAGgCQAGgDAEgEQAEgFACgFQACgGAAgHQAAgGgCgGQgCgFgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACg");
	this.shape_90.setTransform(562.35,494.2);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AAPAsIgUglIgLAAIAAAlIgQAAIAAhXIAfAAIAKABQAHACAEADQAEADADAEQADAFAAAHQAAAKgFAGQgGAFgJACIAXAngAgQgFIANAAIAFgBIAGgBQADgCACgCQACgDAAgEQAAgDgCgDIgFgDIgFgCIgFgBIgOAAg");
	this.shape_91.setTransform(554.1,494.225);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgbAsIAAhXIA3AAIAAAOIgnAAIAAAYIAlAAIAAAMIglAAIAAAlg");
	this.shape_92.setTransform(547.025,494.225);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgQArQgJgDgFgHIALgKQADAFAGACQAFADAFAAIAFgBIAFgCIAEgEIABgGQAAgDgCgDIgDgDIgHgEIgHgCIgIgDIgHgEQgDgCgCgFQgCgEAAgGQAAgHADgFQADgFAEgDQAFgDAGgBQAFgCAFAAQAGAAAIADQAHACAFAFIgKALQgDgDgFgDQgEgCgFAAIgEABIgFACIgEAEIgBAFIABAFIAEAEIAEADIAGACIAJACIAIAFQAEACADAEQACAFAAAHQAAAHgCAEQgDAGgFADQgEAEgFACQgHABgFAAQgJAAgHgDg");
	this.shape_93.setTransform(537.4,494.2);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AAgAsIAAhGIgbBGIgKAAIgahGIAAAAIAABGIgPAAIAAhXIAYAAIAWA9IAXg9IAYAAIAABXg");
	this.shape_94.setTransform(528.775,494.225);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgSArQgIgDgHgHQgGgGgEgIQgDgJAAgKQAAgJADgJQAEgJAGgFQAHgHAIgCQAJgEAJAAQAKAAAJAEQAIACAHAHQAGAFAEAJQADAJAAAJQAAAKgDAJQgEAIgGAGQgHAHgIADQgJADgKAAQgJAAgJgDgAgLgdQgGADgEAEQgEAFgCAFQgCAGAAAGQAAAHACAGQACAFAFAFQADAEAGADQAFACAGAAQAGAAAGgCQAGgDAEgEQAEgFACgFQACgGAAgHQAAgGgCgGQgCgFgEgFQgEgEgGgDQgFgCgHAAQgGAAgFACg");
	this.shape_95.setTransform(518.35,494.2);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AgSArQgIgDgHgHQgGgGgDgIQgEgJAAgKQAAgJAEgJQADgJAGgFQAHgHAIgCQAJgEAJAAQAKAAAJAEQAIACAHAHQAGAFAEAJQADAJAAAJQAAAKgDAJQgEAIgGAGQgHAHgIADQgJADgKAAQgJAAgJgDgAgMgdQgFADgEAEQgEAFgCAFQgCAGAAAGQAAAHACAGQACAFAEAFQAEAEAGADQAFACAGAAQAGAAAGgCQAGgDAEgEQAEgFACgFQACgGAAgHQAAgGgCgGQgCgFgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACg");
	this.shape_96.setTransform(508.35,494.2);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AAOAsIgTglIgLAAIAAAlIgQAAIAAhXIAeAAIAMABQAFACAFADQAFADACAEQADAFAAAHQAAAKgGAGQgFAFgJACIAXAngAgQgFIAMAAIAGgBIAGgBQADgCABgCQACgDAAgEQAAgDgCgDIgDgDIgGgCIgFgBIgOAAg");
	this.shape_97.setTransform(500.05,494.225);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0368D9").s().p("AANBYIghg/IgCAAIAAA/Ig6AAIAAivIBNAAQALgBANADQANADAKAGQAKAHAHALQAGALAAARQAAAQgIAMQgIAMgPAGIAtBIgAgXgNIAMAAIAHgBIAFgBQAEgCACgDQACgDAAgFQAAgEgCgDIgEgEIgFgCIgGAAIgPAAg");
	this.shape_98.setTransform(-116.575,466.75);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#0368D9").s().p("Ag+BYIAAivIB5AAIAAAxIhBAAIAAAPIA9AAIAAAtIg9AAIAAARIBFAAIAAAxg");
	this.shape_99.setTransform(-133.4,466.75);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#0368D9").s().p("Ag7BYIAAivIB3AAIAAAxIg9AAIAAASIA2AAIAAAxIg1AAIAAA7g");
	this.shape_100.setTransform(-148.225,466.75);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#0368D9").s().p("Ag7BYIAAivIB3AAIAAAxIg9AAIAAASIA2AAIAAAxIg1AAIAAA7g");
	this.shape_101.setTransform(-162.725,466.75);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#0368D9").s().p("AgmBXQgSgHgNgNQgNgMgIgRQgHgRAAgVQAAgVAHgSQAIgQANgNQANgLASgHQASgGAUgBQAVABASAGQASAHANALQAOANAHAQQAHASAAAVQAAAVgHARQgHARgOAMQgNANgSAHQgSAGgVABQgUgBgSgGgAgNgjQgGADgFAEQgFAFgCAIQgDAGAAAJQAAAIADAHQACAHAFAGQAFAEAGAEQAGADAHAAQAIAAAGgDQAGgEAFgEQAFgGACgHQADgHAAgIQAAgJgDgGQgCgIgFgFQgFgEgGgDQgGgDgIAAQgHAAgGADg");
	this.shape_102.setTransform(-181.025,466.75);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#0368D9").s().p("AgYBXQgSgHgNgMQgNgMgIgRQgHgSAAgVQAAgUAHgRQAIgSANgMQANgMARgHQASgGATAAQAUAAATAGQATAHALAMIgiAqQgGgHgHgEQgIgEgLAAQgHAAgHADQgGADgFAGQgFAFgEAIQgDAHAAAIQAAATAKALQAJAMAVAAIAIgBIAGgBIAAgOIgdAAIAAguIBRAAIAABgIgOAHIgRAFIgTAEIgUABQgUAAgSgGg");
	this.shape_103.setTransform(-207.725,466.725);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#0368D9").s().p("AAVBYIgvhUIgBAAIACBUIg4AAIAAivIA7AAIAxBYIABAAIgChYIA4AAIAACvg");
	this.shape_104.setTransform(-226.85,466.75);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#0368D9").s().p("AgdBYIAAivIA7AAIAACvg");
	this.shape_105.setTransform(-241.4,466.75);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#0368D9").s().p("Ag7BYIAAivIA8AAIAAB8IA6AAIAAAzg");
	this.shape_106.setTransform(-252.15,466.75);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#0368D9").s().p("Ag7BYIAAivIA8AAIAAB8IA6AAIAAAzg");
	this.shape_107.setTransform(-265.85,466.75);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#0368D9").s().p("AgdBYIAAivIA7AAIAACvg");
	this.shape_108.setTransform(-278.1,466.75);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#0368D9").s().p("AANBYIghg/IgCAAIAAA/Ig6AAIAAivIBNAAQALgBANADQANADAKAGQAKAHAHALQAGALAAARQAAAQgIAMQgIAMgPAGIAtBIgAgXgNIAMAAIAHgBIAFgBQAEgCACgDQACgDAAgFQAAgEgCgDIgEgEIgFgCIgGAAIgPAAg");
	this.shape_109.setTransform(-290.875,466.75);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#0368D9").s().p("AAYBYIAAhDIgvAAIAABDIg8AAIAAivIA8AAIAAA7IAvAAIAAg7IA8AAIAACvg");
	this.shape_110.setTransform(-310.625,466.75);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#0368D9").s().p("AgcBYIAAh9IgsAAIAAgyICRAAIAAAyIgrAAIAAB9g");
	this.shape_111.setTransform(-328.175,466.75);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#E5C554").s().p("A0ZCgIAAk/MAoyAAAIAAE/g");
	this.shape_112.setTransform(-222.05,466.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]},7).wait(124));

	// BTN
	this.instance_1 = new lib.BTN();
	this.instance_1.setTransform(150.15,575.75,0.8049,0.8049,0,0,0,0.1,0.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(7).to({_off:false},0).wait(124));

	// thrillingAnimation_copy
	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#0368D9").s().p("AFlBWQgRgHgOgMQgMgMgIgSQgHgRgBgUQABgVAHgRQAIgRAMgMQANgMASgGQASgHAVAAQAUAAASAHQASAGAOAMQANAMAHARQAIARAAAVQAAAUgIARQgHASgNAMQgOAMgSAHQgSAHgUAAQgVAAgSgHgAF+gjQgHADgEAFQgFAEgDAIQgCAHAAAIQAAAIACAHQADAHAFAFQAEAFAHADQAGADAIAAQAHAAAGgDQAHgDAFgFQAEgFADgHQADgHAAgIQAAgIgDgHQgDgHgEgFQgFgFgHgDQgGgDgHAAQgIAAgGADgABxBWQgRgHgOgMQgMgMgIgRQgHgRAAgVQAAgUAHgRQAHgRANgMQANgMARgHQASgHATAAQAVAAATAHQASAHALALIgiAqQgFgHgHgDQgIgEgLAAQgHAAgHADQgHACgFAGQgFAFgEAHQgCAIAAAIQAAASAJAMQAKALAUAAIAIAAIAHgCIAAgNIgdAAIAAguIBQAAIAABfIgNAHIgSAFIgmAFQgWAAgRgGgAQLBYIgig/IgCAAIAAA/Ig5AAIAAivIBMAAQAMAAANADQANADAKAGQAKAHAGALQAGALABAQQgBAQgHANQgJALgPAHIAtBHgAPngNIASAAIAGgCQADgCACgDQACgDAAgEQAAgFgBgDIgEgEIgGgBIgUgBgAMcBYIAAivIB5AAIAAAxIhCAAIAAAPIA9AAIAAAtIg9AAIAAARIBFAAIAAAxgAKQBYIAAivIB2AAIAAAyIg9AAIAAASIA2AAIAAAvIg2AAIAAA8gAIDBYIAAivIB2AAIAAAyIg9AAIAAASIA2AAIAAAvIg1AAIAAA8gAgaBYIgxhUIgBAAIADBUIg4AAIAAivIA7AAIAxBYIACAAIgDhYIA3AAIAACvgAjaBYIAAivIA7AAIAACvgAleBYIAAivIA7AAIAAB8IA6AAIAAAzgAnjBYIAAivIA8AAIAAB8IA5AAIAAAzgAo8BYIAAivIA8AAIAACvgAqNBYIghg/IgCAAIAAA/Ig5AAIAAivIBLAAQANAAANADQANADAKAGQAKAHAGALQAGALAAAQQABAQgJANQgHALgPAHIAsBHgAqxgNIASAAIAHgCQADgCADgDQACgDAAgEQgBgFgBgDIgFgEIgGgBIgUgBgAtCBYIAAhDIgvAAIAABDIg8AAIAAivIA7AAIAAA8IAwAAIAAg8IA8AAIAACvgAwiBYIAAh9IgrAAIAAgyICSAAIAAAyIgrAAIAAB9g");
	this.shape_113.setTransform(150.15,466.525);
	this.shape_113._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_113).wait(78).to({_off:false},0).wait(53));

	// thrillingAnimation
	this.instance_2 = new lib.copyAnimations();
	this.instance_2.setTransform(52.25,126.8,0.6519,0.6519,0,0,0,0.1,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(37).to({_off:false},0).to({_off:true},41).wait(53));

	// thrillBG
	this.instance_3 = new lib.BGanimation();
	this.instance_3.setTransform(150,466.65,0.01,0.0156,0,0,0,5,3.2);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({regX:0,regY:0,scaleX:1.14,scaleY:1.14,x:149.95,y:466.6},10,cjs.Ease.circOut).to({scaleX:1,scaleY:1,x:150,y:466.65},9,cjs.Ease.circOut).wait(97));

	// BGoverlay
	this.instance_4 = new lib.btmOverlay();
	this.instance_4.setTransform(0,338);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(131));

	// circleMask_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EAJ8AqcQgUgDgUgHQgRgIgSgKQgPgKgMgMQgNgNgMgPQgKgRgIgSQgKgUgCgRQgDgUAAgSQAAgRAFgSQAFgUAIgRQAHgSAKgMQANgPAMgNQAPgMAPgKQAPgKAUgIQASgFARgCIAmAAIAjAFQAUAFARAKIAcAUQAPAMAMAPQANAPAHASQAKARAFAUQAFASAAARIAAAKQAAASgCARQgFAUgIASQgHAUgNAPQgMARgNANQgPAMgRAKQgSAKgRAFQgUAFgSADIgUABIgUgBg");
	var mask_graphics_1 = new cjs.Graphics().p("EAJyAqeQgWgDgVgIQgUgIgTgLQgQgLgOgOQgNgNgOgRQgLgTgIgTQgLgVgCgTQgDgWAAgTQAAgTAFgTQAGgWAIgTQAIgTALgOQAOgQANgOQARgOAQgKQAQgLAWgIQATgGATgDIApAAIAmAGQAWAFATALQAQALAOALQAQAOAOAQQANAQAJATQAKATAGAWQAFATAAATIAAALQAAATgCATQgGAWgIATQgIAWgOAQQgNATgOAOQgQAOgTAKQgTALgTAGQgWAFgTADIgWABIgWgBg");
	var mask_graphics_2 = new cjs.Graphics().p("EAJTAqlQgbgDgbgLQgYgKgYgOQgVgNgRgRQgRgRgRgVQgNgYgKgXQgOgcgEgXQgDgcAAgYQAAgXAHgYQAHgbAKgYQAKgYAOgRQARgVARgRQAUgRAVgNQAUgOAbgKQAYgHAYgDIAzAAIAwAGQAbAHAYAOQAUAOARANQAVARARAVQARAUAKAYQAOAYAGAbQAHAYAAAYIAAANQAAAYgDAYQgHAbgKAYQgKAbgRAVQgRAYgRARQgVARgYANQgYAOgXAHQgcAHgXADQgOACgOAAQgNAAgOgCg");
	var mask_graphics_3 = new cjs.Graphics().p("EAIdAqxQglgEglgOQgggOgggSQgcgTgXgXQgXgXgXgbQgSghgOggQgSglgFggQgEgkAAghQAAggAJggQAJglAOggQAOggASgXQAXgcAXgXQAcgXAbgSQAcgSAlgOQAggJAggFIBFAAIBAAJQAlAJAgATQAcASAXATQAbAXAXAbQAXAcAOAgQASAgAKAlQAJAgAAAgIAAATQAAAggFAgQgJAlgOAgQgOAlgXAbQgXAggXAXQgbAXggATQggASghAJQgkAKghAEQgSACgSAAQgTAAgSgCg");
	var mask_graphics_4 = new cjs.Graphics().p("EAHLArEQgzgHgzgTQgtgTgtgaQgmgZggggQgggggggnQgagtgTgsQgagzgGgtQgGgzAAgtQAAgtAMgtQANgzATgtQAUgsAZggQAggnAgggQAmggAngZQAmgaAzgTQAtgNAtgGIBgAAIBZAMQA0ANAsAaQAnAZAgAaQAmAgAgAmQAgAnATAsQAaAtANAzQAMAtAAAtIAAAaQAAAsgGAtQgNAzgTAtQgTAzggAnQggAsggAgQgmAggtAaQgtAagtAMQgzANgtAHQgZADgaAAQgZAAgagDg");
	var mask_graphics_5 = new cjs.Graphics().p("EAFUAreQhJgJhIgbQg/gbg/gkQg2gkgsgtQgtgtgug2Qgkg/gbhAQgkhIgJg/QgJhIAAg/QAAg/ASg/QAShJAbg/QAbg/AkgtQAug2AtgtQA1gtA2gkQA2glBIgbQA/gSBAgJICHAAIB+ASQBIASA/AkQA3AlAtAkQA2AtAtA2QAtA2AbA/QAkA/ASBIQASBAAAA/IAAAkQAAA/gJA/QgSBIgbBAQgbBIgtA2QgtA/gtAtQg2AthAAkQg/Akg/ASQhIASg/AJQgkAFgkAAQgkAAgkgFg");
	var mask_graphics_6 = new cjs.Graphics().p("EACdAsIQhogNhogoQhbgnhbg0QhOg0hChBQhBhBhBhPQg0hbgnhbQg0hogNhcQgNhoAAhbQAAhbAahcQAahoAnhbQAnhbA0hCQBBhOBBhBQBPhBBOg0QBOg0BogoQBbgaBbgNIDDAAIC3AaQBoAaBbA1QBPA0BBA0QBOBBBBBOQBBBOAoBcQA0BbAaBoQAaBcAABbIAAA0QAABbgNBbQgaBpgnBbQgoBohBBOQhBBchBBBQhOBBhcA0QhbA0hbAaQhoAbhcANQg0AGg0AAQg0AAg0gGg");
	var mask_graphics_7 = new cjs.Graphics().p("EgDZAt6QjCgYjChJQiphIiqhhQiRhhh5h5Qh6h5h5iSQhhiphIiqQhhjCgYipQgZjCAAiqQAAipAxiqQAwjCBJipQBJiqBhh5QB5iRB5h5QCRh5CShhQCRhhDChIQCpgxCqgYIFqAAIFUAwQDBAxCqBhQCRBhB5BhQCSB5B5CQQB5CSBJCpQBhCqAwDCQAxCpAACqIAABhQAACpgZCqQgwDChJCpQhIDCh6CRQh5Cqh5B5QiRB5iqBhQipBhiqAxQjCAwipAYQhhAMhgAAQhhAAhhgMg");
	var mask_graphics_8 = new cjs.Graphics().p("EgE+AvtQkbgjkbhrQj4hqj4iOQjViNixixQixiyixjUQiOj4hqj4QiOkbgjj4QgkkcAAj4QAAj3BHj3QBHkcBqj4QBrj4CNixQCxjUCxixQDVixDUiOQDViOEbhqQD4hHD4gjIITAAIHvBHQEcBGD4COQDUCOCxCNQDVCyCxDUQCxDVBqD3QCOD4BHEcQBHD3AAD4IAACNQAAD4gkD4QhHEchqD3QhqEcixDUQixD4ixCxQjVCxj4COQj4COj4BHQkbBHj4AjQiOASiMAAQiOAAiOgSg");
	var mask_graphics_9 = new cjs.Graphics().p("EgFiAwWQk7gnk8h3QkUh2kUieQjtidjFjGQjFjFjFjsQiekUh2kUQiek8gnkUQgok7AAkUQAAkUBPkUQBPk7B2kUQB3kUCdjFQDGjtDFjFQDsjFDtieQDtieE7h2QEUhPEUgnIJPAAIIoBPQE7BOEUCeQDtCeDFCeQDtDFDFDsQDFDtB2EUQCeEUBPE8QBPEUAAETIAACdQAAEUgoEUQhPE8h2EUQh2E7jFDtQjGEUjFDFQjsDFkUCeQkUCekUBPQk8BPkUAnQieAUicAAQieAAiegUg");
	var mask_graphics_10 = new cjs.Graphics().p("EgF6AwxQlQgqlQh+Qknh+kmipQj9iojSjSQjSjTjTj8Qiokmh+knQiolQgqknQgqlQAAklQAAknBUkmQBUlRB+kmQB+knCpjSQDSj8DSjTQD8jSD9ioQD8ioFRh+QEmhVEmgqIJ2AAIJNBUQFRBVEmCoQD8CoDTCoQD8DTDSD8QDTD8B+EnQCoEmBUFRQBUEmAAEmIAACoQAAEmgqEmQhUFRh+EmQh+FRjTD8QjSEnjSDSQj8DSknCoQkmCpknBUQlQBUknAqQioAVinAAQioAAipgVg");
	var mask_graphics_11 = new cjs.Graphics().p("EgGKAx3QlfgsleiEQkziDk0iwQkHivjbjbQjbjcjckHQivkziEkzQivlfgskzQgslfAAkyQAAkzBYkzQBYlfCDkzQCEkzCvjbQDckHDbjbQEHjcEHivQEHiwFfiDQEzhYEzgsIKRAAIJmBYQFfBYEzCvQEHCwDcCvQEHDbDbEIQDbEHCEEzQCvEzBYFfQBYEzAAEzIAACvQAAEygsEzQhYFfiDEzQiEFfjbEHQjcEzjbDbQkHDckzCvQkzCvkzBYQlfBYkzAsQivAWivAAQivAAiwgWg");
	var mask_graphics_12 = new cjs.Graphics().p("EgGUAzNQlpgtloiHQk8iHk7i0QkOi0jijiQjhjhjhkOQi0k8iHk7Qi1logtk8QgtloAAk6QAAk8Bak7QBbloCHk8QCHk7C0jhQDhkPDijhQEOjhEOi0QEOi1FpiHQE7haE8gtIKiAAIJ3BaQFoBaE8C0QEOC1DhC0QEPDhDhEOQDhEPCHE7QC0E7BbFpQBaE7AAE8IAAC0QAAE6gtE7QhaFpiIE7QiHFpjhEOQjhE7jiDhQkODik7C0Qk8C0k7BaQloBak8AtQi0AXizAAQi0AAi0gXg");
	var mask_graphics_13 = new cjs.Graphics().p("EgGbAz/QltguluiJQlAiJlBi3QkSi3jljlQjkjkjlkTQi3lAiJlAQi3lugulAQguluAAk/QAAlABclAQBbluCKlAQCJlAC3jlQDkkSDljlQESjlETi3QESi3FuiJQFAhbFAguIKtAAIKBBcQFuBbFAC3QESC3DlC3QESDkDlETQDkESCKFAQC3FBBbFtQBcFBAAFAIAAC3QAAE/guFAQhcFuiJFAQiJFujlESQjkFAjlDlQkSDllBC2QlAC3lABcQluBblAAuQi3AXi2AAQi3AAi3gXg");
	var mask_graphics_14 = new cjs.Graphics().p("EgGdA0PQlvgulwiKQlCiJlBi4QkUi4jmjmQjmjmjlkTQi4lCiKlCQi4lvgulCQgulwAAlAQAAlCBclCQBclvCKlCQCKlCC4jmQDlkTDmjmQEUjmEUi4QETi4FwiJQFChcFBguIKxAAIKDBcQFwBcFBC3QEUC4DmC4QEUDmDlEUQDmETCKFCQC4FCBcFvQBcFCAAFCIAAC4QAAFAguFCQhcFwiKFBQiKFwjmEUQjlFBjmDmQkUDmlCC4QlBC4lCBbQlwBclBAuQi4AXi3AAQi4AAi4gXg");
	var mask_graphics_78 = new cjs.Graphics().p("EAJ8AqcQgUgDgUgHQgRgIgSgKQgPgKgMgMQgNgNgMgPQgKgRgIgSQgKgUgCgRQgDgUAAgSQAAgRAFgSQAFgUAIgRQAHgSAKgMQANgPAMgNQAPgMAPgKQAPgKAUgIQASgFARgCIAmAAIAjAFQAUAFARAKIAcAUQAPAMAMAPQANAPAHASQAKARAFAUQAFASAAARIAAAKQAAASgCARQgFAUgIASQgHAUgNAPQgMARgNANQgPAMgRAKQgSAKgRAFQgUAFgSADIgUABIgUgBg");
	var mask_graphics_79 = new cjs.Graphics().p("EAJyAqeQgWgDgWgIQgTgIgTgLQgQgLgOgOQgNgNgOgRQgLgTgIgTQgLgWgCgTQgDgVAAgUQAAgTAFgTQAGgVAIgUQAIgTALgNQAOgRANgNQAQgOARgLQAQgLAWgIQATgFATgDIApAAIAmAGQAWAFATALQAQALAOALQAQANAOARQANAQAJATQAKATAGAWQAFATAAATIAAALQAAATgCATQgGAWgIATQgIAWgOAQQgNATgOAOQgQANgTALQgTALgUAGQgVAFgTADIgWABIgWgBg");
	var mask_graphics_80 = new cjs.Graphics().p("EAJTAqkQgbgDgcgLQgXgKgYgOQgVgNgRgRQgRgRgRgVQgNgXgLgYQgNgcgEgXQgDgcAAgXQAAgYAHgYQAHgbAKgYQAKgYAOgRQARgVARgRQAUgRAUgNQAVgOAbgKQAYgHAYgDIAzAAIAwAHQAbAGAYAOQAUAOARANQAVARARAVQARAUAKAYQAOAYAGAbQAHAYAAAYIAAANQAAAYgDAYQgHAbgKAYQgLAbgRAVQgRAYgRARQgUARgYANQgYAOgYAHQgbAHgYADQgNACgOAAQgOAAgNgCg");
	var mask_graphics_81 = new cjs.Graphics().p("EAIcAqvQgkgFglgNQgggOgggTQgcgSgXgXQgXgXgXgcQgSgggOggQgTglgEggQgFglAAggQAAggAJggQAKglANggQAOggATgXQAXgcAXgXQAbgXAcgSQAbgTAlgNQAggKAggEIBFAAIBBAJQAkAJAhATQAbASAXASQAcAXAXAcQAXAbAOAhQASAgAJAlQAJAgAAAgIAAASQAAAhgEAgQgJAkgOAhQgOAkgXAcQgXAggXAXQgcAXggATQggASggAJQglAJggAFQgSACgTAAQgSAAgTgCg");
	var mask_graphics_82 = new cjs.Graphics().p("EAHKAq/QgzgGgzgTQgtgTgtgaQgmgaggggQgggfgggnQgagtgTgsQgZg0gHgsQgGg0AAgsQAAgtANgtQAMgzAUgtQATgtAZggQAggmAgggQAnggAmgaQAmgZA0gTQAsgNAtgHIBgAAIBaANQAzANAtAaQAmAZAgAaQAmAgAgAmQAgAnAUAsQAZAtANAzQANAtAAAtIAAAZQAAAtgHAtQgNAzgTAtQgTAzggAnQggAsggAgQgmAggtAaQgtAZgtANQgzANgtAGQgZAEgaAAQgZAAgagEg");
	var mask_graphics_83 = new cjs.Graphics().p("EAFSArYQhIgJhIgcQg/gbg/gkQg3gkgsgtQgtgtgtg2Qgkg/gbg/QgkhJgJg/QgJhIAAg/QAAg/ASg/QAShJAbg/QAbg/AkgtQAtg2AtgtQA1gtA3gkQA2gkBIgcQA/gSA/gJICHAAIB/ASQBIASA/AlQA2AkAtAkQA2AtAuA2QAtA2AbA/QAkA/ASBJQASA/AAA/IAAAkQAAA/gJA/QgSBIgbBAQgbBIgtA2QgtA/guAtQg2Atg/AkQg/Akg/ASQhIATg/AJQglAEgkAAQgkAAgkgEg");
	var mask_graphics_84 = new cjs.Graphics().p("EACbAr8QhpgNhngnQhbgnhbg0QhPg0hBhBQhBhBhBhPQg0hbgnhbQg1hogNhcQgNhoAAhbQAAhcAahbQAahoAohbQAnhcA0hBQBBhOBBhBQBOhBBPg1QBOg0BognQBagaBcgNIDDAAIC3AaQBoAaBbA0QBOA1BCA0QBOBBBBBOQBBBOAnBcQA1BbAaBoQAaBbAABcIAAA0QAABbgNBbQgaBpgoBbQgnBohBBOQhBBchBBBQhOBBhcA0QhbA0hbAaQhoAahcANQg0AHg0AAQg0AAg0gHg");
	var mask_graphics_85 = new cjs.Graphics().p("EgDZAtjQjCgYjChJQiphIiqhhQiRhhh5h5Qh6h5h5iSQhhiphIiqQhhjCgYipQgZjCAAiqQAAipAxiqQAwjCBJipQBJiqBhh5QB5iRB5h5QCRh5CShhQCRhhDChIQCpgxCqgYIFqAAIFUAwQDBAxCqBhQCRBhB5BhQCSB5B5CQQB5CSBJCpQBhCqAwDCQAxCpAACqIAABhQAACpgZCqQgwDChJCpQhIDCh6CRQh5Cqh5B5QiRB5iqBhQipBhiqAxQjCAwipAYQhhAMhgAAQhhAAhhgMg");
	var mask_graphics_86 = new cjs.Graphics().p("EgE+AvKQkbgjkbhrQj4hqj4iNQjViOixixQixixixjVQiOj4hqj4QiOkbgjj4QgkkbAAj4QAAj4BHj3QBHkcBqj4QBrj3CNiyQCxjUCxixQDVixDUiOQDViOEbhqQD4hHD4gjIITAAIHvBHQEcBHD4CNQDUCOCxCOQDVCxCxDUQCxDVBqD4QCOD4BHEbQBHD3AAD4IAACNQAAD4gkD4QhHEchqD4QhqEbixDVQixD3ixCyQjVCxj4CNQj4COj4BHQkbBHj4AjQiOASiMAAQiOAAiOgSg");
	var mask_graphics_87 = new cjs.Graphics().p("EgFiAvvQk7gnk8h3QkUh2kUieQjtidjFjGQjFjFjFjsQiekUh2kVQiek7gnkUQgok8AAkUQAAkTBPkUQBPk7B2kUQB3kUCdjFQDGjtDFjFQDsjFDtieQDtieE7h2QEUhPEUgnIJPAAIIoBOQE7BPEUCeQDtCeDFCeQDtDFDFDsQDFDtB2EUQCeEUBPE7QBPEVAAETIAACdQAAEUgoEUQhPE8h2EUQh2E7jFDtQjGEUjFDFQjsDFkUCeQkUCekUBPQk8BPkUAnQieAUicAAQieAAiegUg");
	var mask_graphics_88 = new cjs.Graphics().p("EgF6AwHQlQgqlQh+Qknh+kmipQj9iojSjSQjSjSjTj9Qiokmh+knQiolQgqkmQgqlRAAklQAAknBUkmQBUlRB+kmQB+kmCpjTQDSj8DSjSQD8jTD9ioQD8ioFRh+QEmhUEmgqIJ2AAIJNBUQFRBUEmCoQD8CoDTCoQD8DTDSD8QDTD8B+EnQCoEmBUFRQBUEmAAEnIAACnQAAEmgqEnQhUFQh+EnQh+FQjTD8QjSEnjSDSQj8DSknCpQkmCoknBUQlQBUknAqQioAVinAAQioAAipgVg");
	var mask_graphics_89 = new cjs.Graphics().p("EgGKAx3QlfgsleiEQkziDk0iwQkHivjbjbQjbjcjckHQivkziEkzQivlfgskzQgslfAAkyQAAkzBYkzQBYlfCDkzQCEkzCvjbQDckHDbjbQEHjcEHivQEHiwFfiDQEzhYEzgsIKRAAIJmBYQFfBYEzCvQEHCwDcCvQEHDbDbEIQDbEHCEEzQCvEzBYFfQBYEzAAEzIAACvQAAEygsEzQhYFfiDEzQiEFfjbEHQjcEzjbDbQkHDckzCvQkzCvkzBYQlfBYkzAsQivAWivAAQivAAiwgWg");
	var mask_graphics_90 = new cjs.Graphics().p("EgGUAzNQlpgtloiHQk8iHk7i0QkOi0jijiQjhjhjhkOQi0k8iHk7Qi1logtk8QgtloAAk6QAAk8Bak7QBbloCHk8QCHk7C0jhQDhkPDijhQEOjhEOi0QEOi1FpiHQE7haE8gtIKiAAIJ3BaQFoBaE8C0QEOC1DhC0QEPDhDhEOQDhEPCHE7QC0E7BbFpQBaE7AAE8IAAC0QAAE6gtE7QhaFpiIE7QiHFpjhEOQjhE7jiDhQkODik7C0Qk8C0k7BaQloBak8AtQi0AXizAAQi0AAi0gXg");
	var mask_graphics_91 = new cjs.Graphics().p("EgGbAz/QltguluiJQlAiJlBi3QkSi3jljlQjkjkjlkTQi3lAiJlAQi3lugulAQguluAAk/QAAlABclAQBbluCKlAQCJlAC3jlQDkkSDljlQESjlETi3QESi3FuiJQFAhbFAguIKtAAIKBBcQFuBbFAC3QESC3DlC3QESDkDlETQDkESCKFAQC3FBBbFtQBcFBAAFAIAAC3QAAE/guFAQhcFuiJFAQiJFujlESQjkFAjlDlQkSDllBC2QlAC3lABcQluBblAAuQi3AXi2AAQi3AAi3gXg");
	var mask_graphics_92 = new cjs.Graphics().p("EgGdA0PQlvgulwiKQlCiJlBi4QkUi4jmjmQjmjmjlkTQi4lCiKlCQi4lvgulCQgulwAAlAQAAlCBclCQBclvCKlCQCKlCC4jmQDlkTDmjmQEUjmEUi4QETi4FwiJQFChcFBguIKxAAIKDBcQFwBcFBC3QEUC4DmC4QEUDmDlEUQDmETCKFCQC4FCBcFvQBcFCAAFCIAAC4QAAFAguFCQhcFwiKFBQiKFwjmEUQjlFBjmDmQkUDmlCC4QlBC4lCBbQlwBclBAuQi4AXi3AAQi4AAi4gXg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:84.125,y:271.6875}).wait(1).to({graphics:mask_graphics_1,x:84.9384,y:271.927}).wait(1).to({graphics:mask_graphics_2,x:87.4309,y:272.6609}).wait(1).to({graphics:mask_graphics_3,x:91.7775,y:273.9406}).wait(1).to({graphics:mask_graphics_4,x:98.3485,y:275.8753}).wait(1).to({graphics:mask_graphics_5,x:107.9286,y:278.6959}).wait(1).to({graphics:mask_graphics_6,x:122.5826,y:283.0105}).wait(1).to({graphics:mask_graphics_7,x:150,y:295.0376}).wait(1).to({graphics:mask_graphics_8,x:150,y:307.0647}).wait(1).to({graphics:mask_graphics_9,x:150,y:311.3793}).wait(1).to({graphics:mask_graphics_10,x:150,y:314.1999}).wait(1).to({graphics:mask_graphics_11,x:150,y:311.0001}).wait(1).to({graphics:mask_graphics_12,x:150,y:304.8367}).wait(1).to({graphics:mask_graphics_13,x:150,y:301.3023}).wait(1).to({graphics:mask_graphics_14,x:150,y:300.1489}).wait(1).to({graphics:null,x:0,y:0}).wait(63).to({graphics:mask_graphics_78,x:84.125,y:271.6875}).wait(1).to({graphics:mask_graphics_79,x:84.9338,y:271.9034}).wait(1).to({graphics:mask_graphics_80,x:87.4122,y:272.5651}).wait(1).to({graphics:mask_graphics_81,x:91.7341,y:273.7189}).wait(1).to({graphics:mask_graphics_82,x:98.2678,y:275.4632}).wait(1).to({graphics:mask_graphics_83,x:107.7936,y:278.0063}).wait(1).to({graphics:mask_graphics_84,x:122.3644,y:281.8962}).wait(1).to({graphics:mask_graphics_85,x:149.1,y:292.7398}).wait(1).to({graphics:mask_graphics_86,x:148.6364,y:303.5834}).wait(1).to({graphics:mask_graphics_87,x:148.4701,y:307.4733}).wait(1).to({graphics:mask_graphics_88,x:148.3614,y:310.0164}).wait(1).to({graphics:mask_graphics_89,x:148.2868,y:302.2524}).wait(1).to({graphics:mask_graphics_90,x:148.2375,y:295.8371}).wait(1).to({graphics:mask_graphics_91,x:148.2092,y:292.1583}).wait(1).to({graphics:mask_graphics_92,x:148.2,y:300.1489}).wait(1).to({graphics:null,x:0,y:0}).wait(38));

	// IMG_2
	this.instance_5 = new lib.IMG_2();
	this.instance_5.setTransform(150.1,300,1.1,1.1,0,0,0,0.1,300);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(84).to({_off:false},0).to({scaleX:1.05,scaleY:1.05,x:150.05},4,cjs.Ease.circIn).to({regY:299.9,scaleX:1,scaleY:1,y:299.95},31,cjs.Ease.circOut).wait(12));

	// IMG_1
	this.instance_6 = new lib.IMG_1();
	this.instance_6.setTransform(150.05,299.95,1.3,1.3,0,0,0,0.1,299.9);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(6).to({_off:false},0).to({scaleX:1.2,scaleY:1.2,x:149.95,y:299.9},4,cjs.Ease.circIn).to({scaleX:1,scaleY:1,x:150.05,y:299.95},65,cjs.Ease.circOut).to({_off:true},3).wait(53));

	// IMG_1_copy
	this.instance_7 = new lib.IMG_1();
	this.instance_7.setTransform(150.05,299.95,1,1,0,0,0,0.1,299.9);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(78).to({_off:false},0).to({_off:true},14).wait(39));

	// blueOverlay
	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("rgba(3,104,217,0.639)").s().p("EgdQA2nMAAAhtNMA6hAAAMAAABtNg");
	this.shape_114.setTransform(150.025,300.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_114).to({_off:true},14).wait(117));

	// IMG_1_BLUR
	this.instance_8 = new lib.IMG_1();
	this.instance_8.setTransform(150.4,313.8,1.2915,1.2914,0,0,0,0.1,300.1);
	this.instance_8.alpha = 0.5;

	this.instance_9 = new lib.IMG_1();
	this.instance_9.setTransform(147.7,301.4,1.2915,1.2914,0,0,0,0,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8}]}).to({state:[]},14).wait(117));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-202.6,214,810.9,487.1);
// library properties:
lib.properties = {
	id: '2959D62FA5C641B2BA132AE356ACF9F6',
	width: 300,
	height: 600,
	fps: 30,
	color: "#0368D9",
	opacity: 1.00,
	manifest: [
		{src:"images/btmOverlay.png", id:"btmOverlay"},
		{src:"images/imgF1_600.jpg", id:"imgF1_600"},
		{src:"images/imgF2_600.jpg", id:"imgF2_600"},
		{src:"images/UOlogo.png", id:"UOlogo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2959D62FA5C641B2BA132AE356ACF9F6'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;